import type { Note } from "./model";

export const mockNotes: Note[] = [
  {
    id: "note-1",
    title: "Agent loop redesign decisions",
    body: "Key decisions from the Pydantic AI migration review. The deferred rebuild approach is the right call — spec written, engine untouched until Phase 2 lands.",
    label: "engineering",
    tone: "info",
    pinned: true,
    createdAt: "2026-06-05T09:00:00Z",
    updatedAt: "2026-06-07T11:30:00Z",
    checklist: [
      { id: "cl-1", text: "Write spec at docs/spec/", done: true },
      { id: "cl-2", text: "Identify Pydantic AI seams in src/", done: true },
      { id: "cl-3", text: "Prototype tool registry wrapper", done: false },
      { id: "cl-4", text: "Validate streaming integration", done: false },
      { id: "cl-5", text: "Write migration guide", done: false },
    ],
  },
  {
    id: "note-2",
    title: "Infra cost review — June",
    body: "Hetzner CX21: €9.40/mo. Bandwidth overage: €3.00. Total: €12.40. Room to optimize: snapshot policy is retaining 7 days but we only need 2. Could save ~€1.20.",
    label: "ops",
    tone: "warn",
    pinned: true,
    dueAt: "2026-06-15T00:00:00Z",
    createdAt: "2026-06-07T08:05:00Z",
    updatedAt: "2026-06-07T08:05:00Z",
    checklist: [
      { id: "cl-6", text: "Review Hetzner snapshot policy", done: false },
      { id: "cl-7", text: "Check bandwidth anomaly", done: false },
    ],
  },
  {
    id: "note-3",
    title: "Books queue",
    body: "Reading list for the next quarter.",
    label: "personal",
    tone: "dim",
    pinned: false,
    createdAt: "2026-05-20T14:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    checklist: [
      {
        id: "cl-8",
        text: "The Art of Doing Science and Engineering — Hamming",
        done: true,
      },
      {
        id: "cl-9",
        text: "Designing Data-Intensive Applications — Kleppmann",
        done: true,
      },
      { id: "cl-10", text: "Working in Public — Nadia Eghbal", done: false },
      {
        id: "cl-11",
        text: "A Philosophy of Software Design — Ousterhout",
        done: false,
      },
    ],
  },
  {
    id: "note-4",
    title: "Sprint 24 prep notes",
    body: "Items to raise in Thursday planning:\n\n1. API rate limiter: sign-off is blocking the deploy, not the code.\n2. Mobile audit scope: recommend splitting into discovery (S24) + implementation (S25).\n3. Dashboard telemetry: 3 story points is realistic.",
    label: "work",
    tone: "nominal",
    pinned: false,
    dueAt: "2026-06-08T14:00:00Z",
    reminderAt: "2026-06-08T13:00:00Z",
    createdAt: "2026-06-07T13:00:00Z",
    updatedAt: "2026-06-07T13:00:00Z",
  },
  {
    id: "note-5",
    title: "Quick captures",
    body: "Ideas and fragments not yet sorted.\n\n— Explore WAL-mode SQLite for agent session state.\n— Look into SearXNG custom rankers for technical queries.\n— Memory dedup: maybe BM25 prescan before cosine to cut embedding calls?",
    label: "ideas",
    tone: "dim",
    pinned: false,
    createdAt: "2026-06-06T22:00:00Z",
    updatedAt: "2026-06-07T09:15:00Z",
  },
  {
    id: "note-6",
    title: "Post-mortem template",
    body: "Reusable template for P1/P2 post-mortems.\n\n**Timeline** — What happened, in order.\n**Root cause** — Single most proximate cause.\n**Contributing factors** — What made it worse.\n**Action items** — Owner + due date for each.",
    label: "ops",
    tone: "alert",
    pinned: false,
    createdAt: "2026-06-07T07:50:00Z",
    updatedAt: "2026-06-07T07:50:00Z",
  },
];
