"""Artifact surface — list and serve the agent's published previews.

Thin pass-throughs to the artifact store. Metadata (for listing and the
``artifact.published`` event the frontend follows) is separate from the bytes:
``/{id}`` is metadata, ``/{id}/content`` is the file the UI points an iframe or
``<img>`` at. Content is served **inert** — a sandboxing CSP plus ``nosniff`` —
so model-generated HTML can't script the operator's session even if rendered
directly; the frontend should still host it in a sandboxed iframe.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel

from core.exceptions import NotFoundError
from routes import deps
from routes.deps import OPERATOR_ID
from services.artifacts import ArtifactView

router = APIRouter(prefix="/artifacts", tags=["artifacts"])

# Untrusted, model-generated bytes: render with no script execution, a unique
# origin, and no external loads (inline styles + data/self images only).
_PREVIEW_HEADERS = {
    "Content-Security-Policy": (
        "sandbox; default-src 'none'; img-src 'self' data: blob:; "
        "style-src 'unsafe-inline'; font-src 'self' data:"
    ),
    "X-Content-Type-Options": "nosniff",
}


class ArtifactOut(BaseModel):
    id: str
    conversation_id: str
    title: str
    filename: str
    content_type: str
    kind: str
    size: int
    created_at: datetime


def _out(view: ArtifactView) -> ArtifactOut:
    return ArtifactOut(
        id=view.id,
        conversation_id=view.conversation_id,
        title=view.title,
        filename=view.filename,
        content_type=view.content_type,
        kind=view.kind,
        size=view.size,
        created_at=view.created_at,
    )


@router.get("", response_model=list[ArtifactOut])
async def list_artifacts(conversation_id: str, request: Request) -> list[ArtifactOut]:
    views = await deps.artifacts(request).list(OPERATOR_ID, conversation_id)
    return [_out(v) for v in views]


@router.get("/{artifact_id}", response_model=ArtifactOut)
async def get_artifact(artifact_id: str, request: Request) -> ArtifactOut:
    try:
        view = await deps.artifacts(request).get(OPERATOR_ID, artifact_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="artifact not found") from None
    return _out(view)


@router.get("/{artifact_id}/content")
async def get_artifact_content(artifact_id: str, request: Request) -> Response:
    try:
        blob = await deps.artifacts(request).content(OPERATOR_ID, artifact_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="artifact not found") from None
    headers = {**_PREVIEW_HEADERS, "Content-Disposition": f'inline; filename="{blob.filename}"'}
    return Response(content=blob.content, media_type=blob.content_type, headers=headers)
