"""Artifact surface — list and serve the agent's published previews.

Thin pass-throughs to the artifact store. Metadata (for listing and the
``artifact.published`` event the frontend follows) is separate from the bytes:
``/{id}`` is metadata, ``/{id}/content`` is the file the UI points an iframe or
``<img>`` at. Content is served **inert** — a sandboxing CSP plus ``nosniff`` —
so model-generated HTML can't script the operator's session even if rendered
directly; the frontend should still host it in a sandboxed iframe.
"""

from __future__ import annotations

import re
from datetime import datetime
from urllib.parse import quote

from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel, ConfigDict

from core.exceptions import NotFoundError
from routes import deps
from routes.deps import OPERATOR_ID

router = APIRouter(prefix="/artifacts", tags=["artifacts"])

# Untrusted, model-generated bytes: render with no script execution, a unique
# origin, and no external loads (inline styles + data/self images only).
_PREVIEW_HEADERS = {
    "Content-Security-Policy": (
        "sandbox; default-src 'none'; img-src 'self' data: blob:; "
        "style-src 'unsafe-inline'; font-src 'self' data:"
    ),
    "X-Content-Type-Options": "nosniff",
}


class ArtifactOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)  # built straight from an ArtifactView

    id: str
    conversation_id: str
    title: str
    filename: str
    content_type: str
    kind: str
    size: int
    created_at: datetime


def _content_disposition(filename: str) -> str:
    """A safe inline Content-Disposition for an agent-chosen (untrusted) filename.

    The quoted form is reduced to a conservative ASCII token (so a ``"`` or
    newline can't break out of the header or inject another), and the full name
    rides in the RFC 5987 ``filename*`` field, percent-encoded."""
    ascii_token = re.sub(r"[^A-Za-z0-9._-]", "_", filename) or "artifact"
    return f"inline; filename=\"{ascii_token}\"; filename*=UTF-8''{quote(filename, safe='')}"


@router.get("", response_model=list[ArtifactOut])
async def list_artifacts(conversation_id: str, request: Request) -> list[ArtifactOut]:
    views = await deps.artifacts(request).list(OPERATOR_ID, conversation_id)
    return [ArtifactOut.model_validate(v) for v in views]


@router.get("/{artifact_id}", response_model=ArtifactOut)
async def get_artifact(artifact_id: str, request: Request) -> ArtifactOut:
    try:
        view = await deps.artifacts(request).get(OPERATOR_ID, artifact_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="artifact not found") from None
    return ArtifactOut.model_validate(view)


@router.get("/{artifact_id}/content")
async def get_artifact_content(artifact_id: str, request: Request) -> Response:
    try:
        blob = await deps.artifacts(request).content(OPERATOR_ID, artifact_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="artifact not found") from None
    headers = {**_PREVIEW_HEADERS, "Content-Disposition": _content_disposition(blob.filename)}
    return Response(content=blob.content, media_type=blob.content_type, headers=headers)
