"""View surface — list and serve the static versions of a conversation's View.

Thin pass-throughs to the version store (the artifact store under the hood). A
View is one canvas per conversation: a live head (reverse-proxied at
``/previews/{token}/``) plus a history of snapshot **versions**, which this router
serves. Metadata is separate from bytes: ``/{id}`` is metadata, ``/{id}/content``
is the file the UI points an iframe or ``<img>`` at. Content is served **inert** —
a sandboxing CSP plus ``nosniff`` — so model-generated HTML can't script the
operator's session even if rendered directly; the frontend still hosts it in a
sandboxed iframe.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel, ConfigDict

from core.exceptions import NotFoundError
from routes import deps
from routes.deps import OPERATOR_ID
from routes.http import content_disposition

router = APIRouter(prefix="/views", tags=["views"])

# Untrusted, model-generated bytes: render with no script execution, a unique
# origin, and no external loads (inline styles + data/self images only).
_VIEW_HEADERS = {
    "Content-Security-Policy": (
        "sandbox; default-src 'none'; img-src 'self' data: blob:; "
        "style-src 'unsafe-inline'; font-src 'self' data:"
    ),
    "X-Content-Type-Options": "nosniff",
}


class ViewVersionOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)  # built straight from an ArtifactView

    id: str
    conversation_id: str
    title: str
    filename: str
    content_type: str
    kind: str
    size: int
    created_at: datetime


@router.get("", response_model=list[ViewVersionOut])
async def list_versions(conversation_id: str, request: Request) -> list[ViewVersionOut]:
    views = await deps.artifacts(request).list(OPERATOR_ID, conversation_id)
    return [ViewVersionOut.model_validate(v) for v in views]


@router.get("/{version_id}", response_model=ViewVersionOut)
async def get_version(version_id: str, request: Request) -> ViewVersionOut:
    try:
        view = await deps.artifacts(request).get(OPERATOR_ID, version_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="view version not found") from None
    return ViewVersionOut.model_validate(view)


@router.get("/{version_id}/content")
async def get_version_content(version_id: str, request: Request) -> Response:
    try:
        blob = await deps.artifacts(request).content(OPERATOR_ID, version_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="view version not found") from None
    headers = {
        **_VIEW_HEADERS,
        "Content-Disposition": content_disposition(
            blob.filename, inline=True, fallback="view"
        ),
    }
    return Response(content=blob.content, media_type=blob.content_type, headers=headers)
