"""View surface — list a conversation's versions and serve their preview bytes.

Thin pass-throughs to the workspace-history store (the versions + their files/diffs)
and the artifact store (a version's static preview bytes). A View is one canvas per
conversation: a history of **versions** plus an optional live head (reverse-proxied
at ``/previews/{token}/``). ``/snapshots/{id}/…`` browses a version's code/diffs;
``/{artifact_id}/content`` is the preview file the UI points an iframe or ``<img>``
at. Content is served **inert** — a sandboxing CSP plus ``nosniff`` — so
model-generated HTML can't script the operator's session even if rendered directly;
the frontend still hosts it in a sandboxed iframe.
"""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, HTTPException, Request, Response
from pydantic import BaseModel, ConfigDict

from core.exceptions import NotFoundError
from routes import deps
from routes.deps import OPERATOR_ID
from routes.http import content_disposition
from services.artifacts import guess_content_type

router = APIRouter(prefix="/views", tags=["views"])

# Untrusted, model-generated bytes: render with no script execution, a unique
# origin, and no external loads (inline styles + data/self images only).
_VIEW_HEADERS = {
    "Content-Security-Policy": (
        "sandbox; default-src 'none'; img-src 'self' data: blob:; "
        "style-src 'unsafe-inline'; font-src 'self' data:"
    ),
    "X-Content-Type-Options": "nosniff",
}


# --- git-style history: per-turn workspace snapshots ------------------------
# Declared before the dynamic ``/{artifact_id}`` route so ``/snapshots`` isn't
# captured as an artifact id.
class SnapshotOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)  # built from a SnapshotView

    id: str
    conversation_id: str
    title: str | None
    created_at: datetime
    files_changed: int
    summary: str
    # How this version previews: the captured-bytes artifact + its render kind for a
    # `show(file=…)`, both null for a live/auto preview.
    preview_artifact_id: str | None
    preview_kind: str | None
    # The operator's durable bookmark on this version.
    keeper: bool


class KeeperUpdate(BaseModel):
    keeper: bool


class SnapshotFileOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    path: str
    status: str  # "added" | "modified" | "unchanged"


class SnapshotDiffOut(BaseModel):
    model_config = ConfigDict(from_attributes=True)

    path: str
    status: str  # "added" | "modified" | "removed"
    diff: str  # unified diff; empty for a binary file


@router.get("/snapshots", response_model=list[SnapshotOut])
async def list_snapshots(conversation_id: str, request: Request) -> list[SnapshotOut]:
    snapshots = await deps.workspace_history(request).list(OPERATOR_ID, conversation_id)
    return [SnapshotOut.model_validate(s) for s in snapshots]


@router.post("/snapshots/{snapshot_id}/keeper", status_code=204)
async def set_snapshot_keeper(
    snapshot_id: str, body: KeeperUpdate, request: Request
) -> None:
    """Bookmark or unbookmark a version — a durable keeper in an otherwise disposable
    timeline."""
    if not await deps.workspace_history(request).set_keeper(
        OPERATOR_ID, snapshot_id, body.keeper
    ):
        raise HTTPException(status_code=404, detail="snapshot not found")


@router.get("/snapshots/{snapshot_id}/files", response_model=list[SnapshotFileOut])
async def list_snapshot_files(snapshot_id: str, request: Request) -> list[SnapshotFileOut]:
    try:
        files = await deps.workspace_history(request).files(OPERATOR_ID, snapshot_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="snapshot not found") from None
    return [SnapshotFileOut.model_validate(f) for f in files]


@router.get("/snapshots/{snapshot_id}/file")
async def get_snapshot_file(snapshot_id: str, path: str, request: Request) -> Response:
    try:
        content = await deps.workspace_history(request).file_bytes(OPERATOR_ID, snapshot_id, path)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="snapshot file not found") from None
    name = path.rsplit("/", 1)[-1]
    headers = {
        **_VIEW_HEADERS,
        "Content-Disposition": content_disposition(name, inline=True, fallback="file"),
    }
    return Response(content=content, media_type=guess_content_type(name), headers=headers)


@router.get("/snapshots/{snapshot_id}/diff", response_model=list[SnapshotDiffOut])
async def get_snapshot_diff(
    snapshot_id: str, request: Request, base: str | None = None
) -> list[SnapshotDiffOut]:
    """Unified diffs of files changed between ``base`` (default: the previous
    snapshot) and this one."""
    try:
        diffs = await deps.workspace_history(request).diff(OPERATOR_ID, snapshot_id, base)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="snapshot not found") from None
    return [SnapshotDiffOut.model_validate(d) for d in diffs]


class LiveStatusOut(BaseModel):
    """Whether a `view.live` head is still reachable. `token` is the one embedded in
    the head's proxied URL (`/previews/{token}/…`) — the frontend already has it, so
    no conversation id is needed to ask. ``"running"`` = still up; ``"stopped"`` = torn
    down without an explicit `view_close` (the sandbox idle-reaped it, or the
    conversation was purged) — the operator gets a legible reason instead of a bare
    404; ``"unknown"`` = neither (an explicit close, or the process restarted)."""

    status: str  # "running" | "stopped" | "unknown"


@router.get("/live/status", response_model=LiveStatusOut)
async def get_live_status(token: str, request: Request) -> LiveStatusOut:
    sessions = deps.sandbox_sessions(request)
    if sessions is None:
        return LiveStatusOut(status="unknown")
    return LiveStatusOut(status=sessions.preview_status(token))


@router.get("/{artifact_id}/content")
async def get_preview_content(artifact_id: str, request: Request) -> Response:
    """Serve a version's static preview bytes — the captured file a ``show(file=…)``
    stamped on the version (``preview_artifact_id``)."""
    try:
        blob = await deps.artifacts(request).content(OPERATOR_ID, artifact_id)
    except NotFoundError:
        raise HTTPException(status_code=404, detail="view preview not found") from None
    headers = {
        **_VIEW_HEADERS,
        "Content-Disposition": content_disposition(
            blob.filename, inline=True, fallback="view"
        ),
    }
    return Response(content=blob.content, media_type=blob.content_type, headers=headers)
