import type { Skill } from "./model";

export const mockSkills: Skill[] = [
  {
    id: "sk-001",
    name: "Summarize Document",
    description:
      "Condenses a long document into a structured bullet-point summary with key decisions and action items.",
    status: "published",
    trigger: "summarize|condense|tldr",
    body: `## Summarize Document

### Trigger
When the user asks to summarize, condense, or TL;DR a document.

### Procedure
1. Read the full document text.
2. Identify: key decisions, action items, open questions.
3. Output a bullet-point summary grouped under headings.
4. Append a one-sentence executive summary at the top.
5. Keep response under 400 words.

### Example Output
**Executive Summary:** Migration plan approved pending recall validation.
- **Decisions:** Shadow collection approach adopted.
- **Action Items:** Run backfill script off-peak.
- **Open Questions:** Which embedding model to target?`,
    updatedAt: "2026-06-07T14:00:00Z",
    autoGenerated: false,
  },
  {
    id: "sk-002",
    name: "Code Review",
    description:
      "Reviews a code diff for correctness, security issues, and opportunities for simplification.",
    status: "published",
    trigger: "review|code review|diff review",
    body: `## Code Review

### Trigger
When the user pastes a diff or asks for a code review.

### Procedure
1. Parse the diff for changed files and hunks.
2. Check: correctness bugs, security issues (injection, auth bypass), N+1 queries.
3. Check: simplification opportunities, dead code, missing tests.
4. Output findings as a numbered list with severity: HIGH / MED / LOW.
5. For each finding: file, line, description, suggested fix.

### Severity Scale
- HIGH: Bugs that will cause failures or security issues.
- MED: Maintainability or performance problems.
- LOW: Style, naming, cosmetic improvements.`,
    updatedAt: "2026-06-06T20:00:00Z",
    autoGenerated: false,
  },
  {
    id: "sk-003",
    name: "Auto-Tag Memory",
    description:
      "Automatically classifies a new memory entry into user/feedback/project/reference categories.",
    status: "auto",
    trigger: "AUTO: new memory created",
    body: `## Auto-Tag Memory

### Trigger
Automatically run when a new memory entry is created without an explicit type.

### Procedure
1. Read the memory text.
2. Classify into one of: user, feedback, project, reference.
   - user: preferences, habits, communication style.
   - feedback: reactions to assistant outputs.
   - project: technical facts about Odysseus or related systems.
   - reference: tools, conventions, external resources.
3. Return only the type label, no prose.`,
    updatedAt: "2026-06-06T10:00:00Z",
    autoGenerated: true,
  },
  {
    id: "sk-004",
    name: "Research Brief",
    description:
      "Runs a multi-source deep research pass and synthesizes a cited markdown report.",
    status: "published",
    trigger: "research|investigate|deep dive",
    body: `## Research Brief

### Trigger
When the user asks for deep research, a multi-source investigation, or a cited report.

### Procedure
1. Decompose the query into 3–5 focused sub-questions.
2. Run web searches for each sub-question.
3. Fetch and parse top 3 sources per sub-question.
4. Adversarially verify conflicting claims.
5. Synthesize a markdown report with: Executive Summary, Findings (by sub-question), Contradictions, Sources.
6. Cite inline with [n] notation.`,
    updatedAt: "2026-06-05T16:00:00Z",
    autoGenerated: false,
  },
  {
    id: "sk-005",
    name: "Draft Reply",
    description:
      "Generates a professional email reply matching the user's communication style.",
    status: "draft",
    trigger: "reply|draft email|write email",
    body: `## Draft Reply

### Trigger
When the user pastes an email and asks for a draft reply.

### Procedure
1. Read the incoming email: extract sender, subject, key asks.
2. Check memory for user communication preferences.
3. Draft a reply: concise, professional, first-person.
4. Match the tone of the original (formal/casual).
5. Flag any asks that require the user to verify facts.

### Status: DRAFT
This skill is in draft — trigger phrases need tuning.`,
    updatedAt: "2026-06-04T12:00:00Z",
    autoGenerated: false,
  },
  {
    id: "sk-006",
    name: "Auto-Link Documents",
    description:
      "Auto-generated skill that finds cross-references between documents and suggests link insertions.",
    status: "auto",
    trigger: "AUTO: document saved",
    body: `## Auto-Link Documents

### Trigger
Automatically run when a document is saved.

### Procedure
1. Extract named entities from the saved document.
2. Search the document library for matching titles and entities.
3. Return a list of candidate link insertions with anchor text and target doc id.
4. User approves/rejects in the editor.`,
    updatedAt: "2026-06-03T08:00:00Z",
    autoGenerated: true,
  },
];
