/** Skills feature data contracts. */

export type SkillStatus = "published" | "draft" | "auto";

export interface Skill {
  id: string;
  name: string;
  description: string;
  status: SkillStatus;
  trigger: string;
  body: string;
  updatedAt: string;
  autoGenerated: boolean;
}
