/** Skills feature data contracts. */

import type { Status } from "~/ui";

export type SkillStatus = "published" | "draft" | "auto";

export interface Skill {
  id: string;
  name: string;
  description: string;
  status: SkillStatus;
  trigger: string;
  body: string;
  updatedAt: string;
  autoGenerated: boolean;
}

/** Maps a skill's status to its semantic StatusFlag accent. Shared by the
 *  directory and editor so the mapping has a single source of truth. */
export const skillStatusFlag: Record<SkillStatus, Status> = {
  published: "nominal",
  draft: "warn",
  auto: "info",
};
