import type { Album, MediaItem } from "./model";

export const mockAlbums: Album[] = [
  { id: "all", name: "ALL MEDIA", count: 12 },
  { id: "renders", name: "RENDERS", count: 5 },
  { id: "screenshots", name: "SCREENSHOTS", count: 4 },
  { id: "captures", name: "CAPTURES", count: 3 },
];

export const mockMedia: MediaItem[] = [
  {
    id: "m-001",
    title: "neural_grid_v3.png",
    type: "image",
    tags: ["AI", "generated", "grid"],
    favorite: true,
    album: "renders",
    sizeBytes: 4_823_040,
    createdAt: "2026-06-07T10:22:00Z",
  },
  {
    id: "m-002",
    title: "latent_diffusion_01.png",
    type: "image",
    tags: ["diffusion", "abstract"],
    favorite: false,
    album: "renders",
    sizeBytes: 3_145_728,
    createdAt: "2026-06-07T09:14:00Z",
  },
  {
    id: "m-003",
    title: "odysseus_dashboard.png",
    type: "image",
    tags: ["screenshot", "UI"],
    favorite: true,
    album: "screenshots",
    sizeBytes: 1_048_576,
    createdAt: "2026-06-06T22:04:00Z",
  },
  {
    id: "m-004",
    title: "agent_loop_trace.png",
    type: "image",
    tags: ["screenshot", "debug"],
    favorite: false,
    album: "screenshots",
    sizeBytes: 892_928,
    createdAt: "2026-06-06T20:31:00Z",
  },
  {
    id: "m-005",
    title: "render_batch_002.mp4",
    type: "video",
    tags: ["timelapse", "AI"],
    favorite: false,
    album: "renders",
    sizeBytes: 52_428_800,
    createdAt: "2026-06-06T18:00:00Z",
  },
  {
    id: "m-006",
    title: "terminal_capture.png",
    type: "image",
    tags: ["terminal", "log"],
    favorite: false,
    album: "captures",
    sizeBytes: 512_000,
    createdAt: "2026-06-06T16:41:00Z",
  },
  {
    id: "m-007",
    title: "vector_space_viz.png",
    type: "image",
    tags: ["RAG", "embeddings", "viz"],
    favorite: true,
    album: "renders",
    sizeBytes: 2_359_296,
    createdAt: "2026-06-05T14:20:00Z",
  },
  {
    id: "m-008",
    title: "memory_graph.png",
    type: "image",
    tags: ["graph", "memory"],
    favorite: false,
    album: "renders",
    sizeBytes: 1_622_016,
    createdAt: "2026-06-05T11:05:00Z",
  },
  {
    id: "m-009",
    title: "session_replay.mp4",
    type: "video",
    tags: ["session", "capture"],
    favorite: false,
    album: "captures",
    sizeBytes: 89_128_960,
    createdAt: "2026-06-05T09:33:00Z",
  },
  {
    id: "m-010",
    title: "chat_export_view.png",
    type: "image",
    tags: ["screenshot", "export"],
    favorite: false,
    album: "screenshots",
    sizeBytes: 743_424,
    createdAt: "2026-06-04T21:17:00Z",
  },
  {
    id: "m-011",
    title: "research_thread.png",
    type: "image",
    tags: ["screenshot", "research"],
    favorite: false,
    album: "screenshots",
    sizeBytes: 634_880,
    createdAt: "2026-06-04T17:42:00Z",
  },
  {
    id: "m-012",
    title: "workspace_lapse.mp4",
    type: "video",
    tags: ["timelapse", "workspace"],
    favorite: false,
    album: "captures",
    sizeBytes: 130_023_424,
    createdAt: "2026-06-03T08:00:00Z",
  },
];
