import type { Contact } from "./model";

export const mockContacts: Contact[] = [
  {
    id: "ct-1",
    name: "Alex Rivera",
    org: "Freelance",
    emails: ["alex@collaborator.dev", "alex.rivera@gmail.com"],
    phones: ["+1 415 555 0101"],
    notes:
      "Engineering collaborator. Works on Pydantic AI migration. Prefers async Slack > email.",
    synced: true,
    group: "A",
  },
  {
    id: "ct-2",
    name: "Sarah Okonkwo",
    org: "Company Dev",
    emails: ["pm@company.dev"],
    phones: ["+1 650 555 0182"],
    notes:
      "Product manager. Sprint planning contact. Responds fastest to email.",
    synced: true,
    group: "S",
  },
  {
    id: "ct-3",
    name: "Ben Hartmann",
    org: "Hetzner Cloud",
    emails: ["b.hartmann@hetzner.com"],
    phones: [],
    notes: "Account rep for Hetzner. Useful for billing disputes.",
    synced: false,
    group: "B",
  },
  {
    id: "ct-4",
    name: "Clara Mendez",
    org: "Company Dev",
    emails: ["c.mendez@company.dev"],
    phones: ["+34 91 555 0043"],
    notes: "Frontend lead. Coordinates mobile audit.",
    synced: true,
    group: "C",
  },
  {
    id: "ct-5",
    name: "David Park",
    org: "PagerDuty",
    emails: ["d.park@pagerduty.com"],
    phones: ["+1 408 555 0199"],
    notes:
      "Solutions engineer at PagerDuty. Contact for on-call escalation config.",
    synced: false,
    group: "D",
  },
  {
    id: "ct-6",
    name: "Elena Vasquez",
    org: "Freelance",
    emails: ["elena@vsq.io"],
    phones: ["+34 93 555 0077", "+1 212 555 0091"],
    notes: "Design consultant. Last project: redesigned Odysseus admin panel.",
    synced: true,
    group: "E",
  },
  {
    id: "ct-7",
    name: "Felipe Souza",
    org: "Anthropic",
    emails: ["felipe@anthropic.com"],
    phones: [],
    notes: "Reached out about early access program. Follow up after July.",
    synced: false,
    group: "F",
  },
  {
    id: "ct-8",
    name: "Grace Kim",
    org: "Company Dev",
    emails: ["g.kim@company.dev"],
    phones: ["+82 2 555 0134"],
    notes: "DevOps engineer. Handles infra and on-call scheduling.",
    synced: true,
    group: "G",
  },
];
