import { createSignal, For, Show, Suspense, type JSX } from "solid-js";
import {
  Button,
  Drawer,
  EmptyState,
  InstrumentBand,
  ListRow,
  LoadingText,
  Menu,
  PageHeader,
  Panel,
  Row,
  Stack,
  StatusFlag,
  Tabs,
  Text,
  type Status,
} from "~/ui";
import { relativeTime, timestamp } from "~/lib/format";
import { useSkills } from "../data";
import type { Skill, SkillStatus } from "../model";

const statusFlag: Record<SkillStatus, Status> = {
  published: "nominal",
  draft: "warn",
  auto: "info",
};

const STATUS_TABS = [
  { value: "all", label: "ALL" },
  { value: "published", label: "PUBLISHED" },
  { value: "draft", label: "DRAFT" },
  { value: "auto", label: "AUTO" },
];

function SkillDetailDrawer(props: {
  skill: Skill | null;
  onClose: () => void;
}): JSX.Element {
  return (
    <Drawer
      open={props.skill !== null}
      onClose={props.onClose}
      title={props.skill?.name ?? "SKILL"}
      class="max-w-lg"
      footer={
        <Row gap={2}>
          <Button variant="primary" size="sm" leading="play">
            TEST
          </Button>
          <Button variant="ghost" size="sm" onClick={props.onClose}>
            CLOSE
          </Button>
        </Row>
      }
    >
      <Show when={props.skill}>
        {(sk) => (
          <Stack gap={4}>
            <Row gap={2} align="center">
              <StatusFlag status={statusFlag[sk().status]}>
                {sk().status.toUpperCase()}
              </StatusFlag>
              <Show when={sk().autoGenerated}>
                <StatusFlag status="info">AUTO-GENERATED</StatusFlag>
              </Show>
            </Row>

            <Text variant="body" tone="dim">
              {sk().description}
            </Text>

            <div class="border border-line bg-raised p-3">
              <Text variant="label" tone="dim" class="mb-2 block">
                TRIGGER
              </Text>
              <Text variant="body" class="font-mono">
                {sk().trigger}
              </Text>
            </div>

            <div class="flex flex-col gap-2">
              <Text variant="label" tone="dim">
                PROCEDURE BODY
              </Text>
              <div class="border border-line bg-raised p-3 font-mono">
                <Text
                  variant="body"
                  class="whitespace-pre-wrap font-mono leading-relaxed"
                >
                  {sk().body}
                </Text>
              </div>
            </div>

            <Text variant="micro" tone="dim">
              LAST UPDATED {timestamp(sk().updatedAt)}
            </Text>
          </Stack>
        )}
      </Show>
    </Drawer>
  );
}

export function SkillsDirectoryScreen(): JSX.Element {
  const skills = useSkills();
  const [statusFilter, setStatusFilter] = createSignal("all");
  const [activeSkill, setActiveSkill] = createSignal<Skill | null>(null);

  const filtered = () => {
    const all = skills() ?? [];
    const f = statusFilter();
    if (f === "all") return all;
    return all.filter((s) => s.status === f);
  };

  const countOf = (s: SkillStatus) =>
    (skills() ?? []).filter((sk) => sk.status === s).length;

  return (
    <Stack gap={6}>
      <PageHeader
        title="SKILLS"
        subtitle="Reusable procedures the assistant can invoke by trigger phrase."
        assetId="ODY-SKL-01.0"
        actions={
          <Button variant="primary" leading="plus">
            NEW SKILL
          </Button>
        }
      />

      <InstrumentBand
        items={[
          { label: "TOTAL", value: String((skills() ?? []).length) },
          {
            label: "PUBLISHED",
            value: String(countOf("published")),
            tone: "nominal",
          },
          { label: "DRAFT", value: String(countOf("draft")), tone: "warn" },
          { label: "AUTO", value: String(countOf("auto")), tone: "info" },
        ]}
      />

      <Panel flush>
        <div class="border-b border-line">
          <Tabs
            items={STATUS_TABS}
            value={statusFilter()}
            onChange={setStatusFilter}
          />
        </div>

        <Suspense
          fallback={
            <div class="p-4">
              <LoadingText />
            </div>
          }
        >
          <Show
            when={filtered().length}
            fallback={
              <EmptyState
                icon="code"
                message="NO SKILLS"
                hint="No skills match the current filter."
              />
            }
          >
            <For each={filtered()}>
              {(skill) => (
                <ListRow
                  label={skill.name}
                  leading="code"
                  onClick={() => setActiveSkill(skill)}
                  right={
                    <span class="flex items-center gap-3 shrink-0">
                      <Show when={skill.autoGenerated}>
                        <StatusFlag status="info">AUTO</StatusFlag>
                      </Show>
                      <StatusFlag status={statusFlag[skill.status]}>
                        {skill.status.toUpperCase()}
                      </StatusFlag>
                      <Text variant="micro" tone="dim">
                        {relativeTime(skill.updatedAt)}
                      </Text>
                      <Menu
                        trigger={
                          <span class="px-1 text-dim hover:text-bright">
                            <Text variant="micro">···</Text>
                          </span>
                        }
                        items={[
                          {
                            label: "VIEW / EDIT",
                            icon: "edit",
                            onSelect: () => setActiveSkill(skill),
                          },
                          { label: "TEST", icon: "play", onSelect: () => {} },
                          {
                            label:
                              skill.status === "published"
                                ? "UNPUBLISH"
                                : "PUBLISH",
                            icon: "check",
                            onSelect: () => {},
                          },
                          {
                            label: "DELETE",
                            icon: "trash",
                            danger: true,
                            onSelect: () => {},
                          },
                        ]}
                      />
                    </span>
                  }
                />
              )}
            </For>
          </Show>
        </Suspense>
      </Panel>

      <SkillDetailDrawer
        skill={activeSkill()}
        onClose={() => setActiveSkill(null)}
      />
    </Stack>
  );
}
