import { createEffect, createSignal, Show, Suspense, type JSX } from "solid-js";
import { createStore } from "solid-js/store";
import {
  Button,
  EditorShell,
  EmptyState,
  Input,
  LoadingText,
  Panel,
  Stack,
  StatusFlag,
  Text,
  Textarea,
  toast,
} from "~/ui";
import { timestamp } from "~/lib/format";
import { useSkillDetail } from "../data";
import { skillStatusFlag, type Skill, type SkillStatus } from "../model";
import { TestSkillModal } from "../components/TestSkillModal";

interface SkillDraft {
  name: string;
  trigger: string;
  description: string;
  body: string;
  status: SkillStatus;
}

/** Full-page skill editor — same shell/UX as the document editor (back link,
 *  header + dirty/save, body editor, tools aside). */
export function SkillEditorScreen(props: { id: string }): JSX.Element {
  const skill = useSkillDetail(() => props.id);

  const [draft, setDraft] = createStore<SkillDraft>({
    name: "",
    trigger: "",
    description: "",
    body: "",
    status: "draft",
  });
  const [snapshot, setSnapshot] = createSignal("");
  const [showSaved, setShowSaved] = createSignal(false);
  const [testing, setTesting] = createSignal(false);

  // Seed the draft once the skill resolves.
  let seeded = false;
  createEffect(() => {
    const s = skill();
    if (!seeded && s) {
      seeded = true;
      const init: SkillDraft = {
        name: s.name,
        trigger: s.trigger,
        description: s.description,
        body: s.body,
        status: s.status,
      };
      setDraft(init);
      setSnapshot(JSON.stringify(init));
    }
  });

  const currentJson = () =>
    JSON.stringify({
      name: draft.name,
      trigger: draft.trigger,
      description: draft.description,
      body: draft.body,
      status: draft.status,
    });
  const isDirty = () => seeded && currentJson() !== snapshot();

  function handleSave(): void {
    if (!isDirty()) return;
    // Phase 1: mock save — persist snapshot and show feedback.
    setSnapshot(currentJson());
    setShowSaved(true);
    toast.success("Skill saved");
    setTimeout(() => setShowSaved(false), 2000);
  }

  function handlePublishToggle(): void {
    if (draft.status === "auto") {
      toast.warn("Auto-generated skills cannot be published or unpublished.");
      return;
    }
    const next: SkillStatus =
      draft.status === "published" ? "draft" : "published";
    setDraft("status", next);
    toast.success(
      next === "published"
        ? "Skill published."
        : "Skill unpublished — moved to draft.",
    );
  }

  // A Skill built from the live draft, for the test harness.
  const draftAsSkill = (): Skill => ({
    id: props.id,
    name: draft.name,
    description: draft.description,
    status: draft.status,
    trigger: draft.trigger,
    body: draft.body,
    updatedAt: skill()?.updatedAt ?? "",
    autoGenerated: skill()?.autoGenerated ?? false,
  });

  const toolsPanel = () => (
    <>
      <Panel label="DETAILS">
        <Stack gap={3}>
          <Input
            label="NAME"
            value={draft.name}
            onInput={(e) => setDraft("name", e.currentTarget.value)}
          />
          <Input
            label="TRIGGER"
            value={draft.trigger}
            onInput={(e) => setDraft("trigger", e.currentTarget.value)}
            hint="Pipe-separated phrases, e.g. summarize|tldr"
          />
          <Textarea
            label="DESCRIPTION"
            value={draft.description}
            onInput={(e) => setDraft("description", e.currentTarget.value)}
            rows={3}
          />
          <Show when={draft.status === "auto"}>
            <StatusFlag status="info">AUTO-GENERATED</StatusFlag>
          </Show>
        </Stack>
      </Panel>

      <Panel label="ACTIONS">
        <Stack gap={2}>
          <Button
            variant="primary"
            size="sm"
            leading="play"
            block
            onClick={() => setTesting(true)}
          >
            TEST SKILL
          </Button>
          <Show when={draft.status !== "auto"}>
            <Button
              variant="default"
              size="sm"
              leading="check"
              block
              onClick={handlePublishToggle}
            >
              {draft.status === "published" ? "UNPUBLISH" : "PUBLISH"}
            </Button>
          </Show>
        </Stack>
      </Panel>
    </>
  );

  return (
    <Suspense fallback={<LoadingText label="LOADING SKILL" />}>
      <Show
        when={skill()}
        fallback={
          <EmptyState
            icon="code"
            message="SKILL NOT FOUND"
            hint="The requested skill does not exist."
            action={
              <Button variant="default" leading="chevron-left" href="/skills">
                BACK TO SKILLS
              </Button>
            }
          />
        }
      >
        <EditorShell
          backHref="/skills"
          backLabel="BACK TO SKILLS"
          title={draft.name || "—"}
          dirty={isDirty()}
          meta={
            <Text variant="micro" tone="dim">
              UPDATED {skill() ? timestamp(skill()!.updatedAt) : "—"}
            </Text>
          }
          status={
            <StatusFlag status={skillStatusFlag[draft.status]}>
              {draft.status.toUpperCase()}
            </StatusFlag>
          }
          actions={
            <Button
              variant={showSaved() ? "default" : "primary"}
              leading={showSaved() ? "check" : "download"}
              size="sm"
              disabled={!isDirty()}
              onClick={handleSave}
            >
              {showSaved() ? "SAVED" : "SAVE"}
            </Button>
          }
          aside={toolsPanel}
        >
          <Textarea
            value={draft.body}
            onInput={(e) => setDraft("body", e.currentTarget.value)}
            rows={32}
            class="h-full w-full resize-none font-mono text-body"
          />
        </EditorShell>
      </Show>

      <TestSkillModal
        skill={testing() ? draftAsSkill() : null}
        onClose={() => setTesting(false)}
      />
    </Suspense>
  );
}
