"""The sub-agents this installation ships with.

Data, not code — see ``spec.py`` for why. A built-in lives here; one a project declares in
a file is the same record built from frontmatter, and the launcher cannot tell them apart.
Where both exist under one name the project's wins, because a repository that has written
down how *its* reviewer should work knows something this file cannot.

The roster is also the model's only view of what it may launch: the launch tool's
description is generated by joining these ``description`` lines, in this order. So the
order is the order the model reads them in — cheapest and most-used first — and each line
has to earn its place, because every one of them is paid for on every request.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping

from services.subagents.spec import SubagentSpec

EXPLORER = "explorer"
WORKER = "worker"

_EXPLORER_BRIEF = (
    "You are an explorer. Search and read the workspace you have been given and answer "
    "the question you were asked with concrete file paths and quoted evidence.\n\n"
    "You change nothing — you have read access and nothing else, so do not plan around "
    "editing. Be thorough in what you read and narrow in what you report: the agent that "
    "launched you is paying for every line you send back, and it needs the answer, not a "
    "tour of how you found it.\n\n"
    "Report only what you actually found. If the answer is not in the workspace, say so "
    "plainly and say where you looked — a confident guess is worse than nothing here, "
    "because nobody downstream can tell it apart from something you read."
)

_WORKER_BRIEF = (
    "You are a worker. You have your own private copy of the workspace: edit it, run "
    "things in it, and check your own work. Nothing you do here touches the operator's "
    "own files, and nothing you do is visible to anyone until you report.\n\n"
    "Do the task you were given and nothing besides it. Every file you change is merged "
    "back into the workspace you were forked from, so an unrelated edit lands there too "
    "— and a file the other agent changed meanwhile comes back as a conflict rather than "
    "as your version winning.\n\n"
    "Verify before you report: run what the task tells you to run, or the project's own "
    "tests.\n\n"
    "Nobody is in this conversation with you. The operator can see what you are doing and "
    "will be asked to approve anything that reaches past what you were allowed, so an act "
    "that needs permission is worth attempting — but you cannot ask them a question, and "
    "there is no one to resolve an ambiguity for you. If the task turns out to be "
    "underspecified, or needs a decision that is not yours, stop and say so in your "
    "report; the agent that launched you can ask.\n\n"
    "Report what you changed, file by file, what you ran to check it, and — plainly — "
    "whatever you could not finish."
)


#: The built-ins, in the order the model reads them.
BUILTIN: tuple[SubagentSpec, ...] = (
    SubagentSpec(
        name=EXPLORER,
        description=(
            "searches and reads the workspace and reports back with concrete paths and "
            "quoted evidence, changing nothing"
        ),
        brief=_EXPLORER_BRIEF,
        # Read-only by absence rather than by asking: at this level a mutating tool is
        # never offered, which is the only form of read-only that survives a model
        # deciding otherwise.
        permission_ceiling="plan",
        # Its own copy, so the files it reads cannot move underneath it while the agent
        # that launched it carries on working.
        workspace="seed",
    ),
    SubagentSpec(
        name=WORKER,
        description=(
            "changes things, in its own copy of the workspace: it edits, runs and verifies "
            "there, and what it changed is then merged back into yours, with any conflict "
            "reported instead of overwriting your version — say exactly what to change and "
            "how to verify it, because you cannot correct a worker while it runs"
        ),
        brief=_WORKER_BRIEF,
        workspace="fork",
    ),
)


def builtin_roster() -> dict[str, SubagentSpec]:
    """The built-ins by name, as a fresh mapping the caller may merge into."""
    return {spec.name: spec for spec in BUILTIN}


def merged_roster(*layers: Iterable[SubagentSpec]) -> dict[str, SubagentSpec]:
    """Every layer folded into one roster, later layers shadowing earlier ones by name.

    One function rather than a dict update written out at each call site, because the
    shadowing direction is the whole rule and it is not self-evident which way a bare
    ``update`` runs — a project's own definition must win over a built-in, never the
    reverse.
    """
    roster: dict[str, SubagentSpec] = {}
    for layer in layers:
        for spec in layer:
            roster[spec.name] = spec
    return roster


def describe_roster(roster: Mapping[str, SubagentSpec]) -> str:
    """The roster as the model reads it, inside the launch tool's own description.

    Generated rather than written out, so a sub-agent added to this file — or declared by
    the project — is one the model can actually see. The alternative is the failure this
    replaced: a hand-written list that names agents the roster no longer has, and omits
    the ones it does, with nothing to make the two disagree loudly.
    """
    return "\n".join(f"`{name}` — {spec.description}." for name, spec in roster.items())
