import type { RagIndexStats, RagSource } from "./model";

export const mockRagSources: RagSource[] = [
  // ── In-app corpus surfaces (auto-indexed, managed on their own pages) ──────
  {
    id: "surf-documents",
    kind: "surface",
    label: "Documents",
    icon: "file",
    href: "/documents",
    docCount: 128,
    status: "indexed",
    lastIndexedAt: "2026-06-16T21:40:00Z",
  },
  {
    id: "surf-uploads",
    kind: "surface",
    label: "Uploads",
    icon: "upload",
    href: "/uploads",
    docCount: 182,
    status: "indexing",
    lastIndexedAt: "2026-06-17T09:05:00Z",
  },
  {
    id: "surf-gallery",
    kind: "surface",
    label: "Gallery",
    icon: "image",
    href: "/gallery",
    docCount: 64,
    status: "indexed",
    lastIndexedAt: "2026-06-16T18:12:00Z",
  },
  {
    id: "surf-memory",
    kind: "surface",
    label: "Memory",
    icon: "database",
    href: "/memory",
    docCount: 341,
    status: "indexed",
    lastIndexedAt: "2026-06-17T07:55:00Z",
  },
  {
    id: "surf-research",
    kind: "surface",
    label: "Research",
    icon: "research",
    href: "/research",
    docCount: 37,
    status: "indexed",
    lastIndexedAt: "2026-06-15T14:20:00Z",
  },
  // ── Operator-added host folders (crawled and indexed) ─────────────────────
  {
    id: "rs-001",
    kind: "folder",
    label: "/data/personal_docs",
    icon: "archive",
    docCount: 4214,
    status: "indexed",
    lastIndexedAt: "2026-06-07T13:00:00Z",
  },
  {
    id: "rs-003",
    kind: "folder",
    label: "/home/panchi/notes",
    icon: "archive",
    docCount: 74,
    status: "stale",
    lastIndexedAt: "2026-05-28T10:00:00Z",
  },
  {
    id: "rs-004",
    kind: "folder",
    label: "/home/panchi/projects/docs",
    icon: "archive",
    docCount: 0,
    status: "error",
    lastIndexedAt: "2026-06-01T09:15:00Z",
    errorHint: "PATH NOT FOUND",
  },
];

export const mockIndexStats: RagIndexStats = {
  embeddingModel: "all-MiniLM-L6-v2",
  dims: 384,
  totalDocs: 5040,
  totalCollections: 8,
  storeSize: "412.6 MB",
};
