"""added approval grants

Revision ID: 099b0b3b4145
Revises: 95fd6a9dedf2
Create Date: 2026-06-24 21:15:56.837030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '099b0b3b4145'
down_revision: Union[str, Sequence[str], None] = '95fd6a9dedf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_grants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'conversation_id', 'tool_name', name='uq_approval_grant_scope')
    )
    with op.batch_alter_table('approval_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_grants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_grants_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('approval_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_grants_owner_id'))
        batch_op.drop_index(batch_op.f('ix_approval_grants_conversation_id'))

    op.drop_table('approval_grants')
    # ### end Alembic commands ###
