"""Added workspace history snapshots

Revision ID: 134f7d775645
Revises: 76afcd0f1019
Create Date: 2026-06-27 11:20:31.097846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '134f7d775645'
down_revision: Union[str, Sequence[str], None] = '76afcd0f1019'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace_blobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('blob_enc', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sha256', name='uq_workspace_blob_owner_sha')
    )
    with op.batch_alter_table('workspace_blobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_blobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_blobs_sha256'), ['sha256'], unique=False)

    op.create_table('workspace_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('manifest_enc', sa.LargeBinary(), nullable=False),
    sa.Column('stats_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_snapshots_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_snapshots_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_snapshots_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_snapshots_owner_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_snapshots_created_at'))
        batch_op.drop_index(batch_op.f('ix_workspace_snapshots_conversation_id'))

    op.drop_table('workspace_snapshots')
    with op.batch_alter_table('workspace_blobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_blobs_sha256'))
        batch_op.drop_index(batch_op.f('ix_workspace_blobs_owner_id'))

    op.drop_table('workspace_blobs')
    # ### end Alembic commands ###
