"""Added kb_excluded flags and message attachment ids

Revision ID: 1514cfe1db2f
Revises: 7d06dac74ae5
Create Date: 2026-06-20 19:29:48.776013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '1514cfe1db2f'
down_revision: Union[str, Sequence[str], None] = '7d06dac74ae5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # New NOT NULL columns land on already-populated tables, so each carries a
    # server_default to backfill existing rows (mirroring the models' Python defaults:
    # not-excluded, no attachments). env.py doesn't compare server defaults, so leaving
    # them on keeps `alembic check` clean.
    with op.batch_alter_table('corpus_chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kb_excluded', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.create_index(batch_op.f('ix_corpus_chunk_kb_excluded'), ['kb_excluded'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment_ids', sa.JSON(), nullable=False, server_default=sa.text("'[]'")))

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kb_excluded', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('kb_excluded')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('attachment_ids')

    with op.batch_alter_table('corpus_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_chunk_kb_excluded'))
        batch_op.drop_column('kb_excluded')

    # ### end Alembic commands ###
