"""added endpoint health and enabled fields

Revision ID: 3c89e0787781
Revises: 1514cfe1db2f
Create Date: 2026-06-20 21:43:16.433351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '3c89e0787781'
down_revision: Union[str, Sequence[str], None] = '1514cfe1db2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        # server_default backfills existing rows (a NOT NULL add needs one); new rows
        # take the model's Python-side default. Endpoints predating this column are
        # treated as enabled — disabling is an explicit operator action.
        batch_op.add_column(
            sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.true())
        )
        batch_op.add_column(sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_error_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_error_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_checked_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.drop_column('last_checked_at')
        batch_op.drop_column('last_error_detail')
        batch_op.drop_column('last_error_category')
        batch_op.drop_column('last_status')
        batch_op.drop_column('enabled')

    # ### end Alembic commands ###
