"""branched conversation tree

Revision ID: 4ef3ed2e19d2
Revises: d8f9871c9589
Create Date: 2026-06-11 22:56:42.067866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '4ef3ed2e19d2'
down_revision: Union[str, Sequence[str], None] = 'd8f9871c9589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_leaf_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_messages_parent_id_messages', 'messages', ['parent_id'], ['id']
        )

    # ### end Alembic commands ###

    # Backfill the tree from the pre-existing linear histories. In the old model
    # seq was a contiguous 0..N-1 counter per conversation, so each message's
    # predecessor is simply the row at seq-1, and the active leaf is the highest
    # seq. This turns every existing conversation into a single-path (degenerate)
    # tree — identical history, now branchable.
    op.execute(
        """
        UPDATE messages
        SET parent_id = (
            SELECT prev.id FROM messages AS prev
            WHERE prev.conversation_id = messages.conversation_id
              AND prev.seq = messages.seq - 1
        )
        WHERE seq > 0
        """
    )
    op.execute(
        """
        UPDATE conversations
        SET active_leaf_id = (
            SELECT leaf.id FROM messages AS leaf
            WHERE leaf.conversation_id = conversations.id
            ORDER BY leaf.seq DESC LIMIT 1
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('fk_messages_parent_id_messages', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_parent_id'))
        batch_op.drop_column('parent_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('active_leaf_id')

    # ### end Alembic commands ###
