"""add skills

Revision ID: 50b7d09be22a
Revises: 775d4d4c9043
Create Date: 2026-08-09 17:07:27.693314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '50b7d09be22a'
down_revision: Union[str, Sequence[str], None] = '775d4d4c9043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_files',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('skill_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relpath', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('blob_enc', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'relpath', name='uq_skill_files_skill_relpath')
    )
    with op.batch_alter_table('skill_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_files_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skill_files_skill_id'), ['skill_id'], unique=False)

    op.create_table('skills',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allowed_tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compatibility_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extras_json_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_skills_owner_name')
    )
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skills_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_skills_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skills_updated_at'))
        batch_op.drop_index(batch_op.f('ix_skills_source'))
        batch_op.drop_index(batch_op.f('ix_skills_published'))
        batch_op.drop_index(batch_op.f('ix_skills_owner_id'))
        batch_op.drop_index(batch_op.f('ix_skills_name'))
        batch_op.drop_index(batch_op.f('ix_skills_created_at'))

    op.drop_table('skills')
    with op.batch_alter_table('skill_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_files_skill_id'))
        batch_op.drop_index(batch_op.f('ix_skill_files_owner_id'))

    op.drop_table('skill_files')
    # ### end Alembic commands ###
