"""external tool schema — MCP servers, integrations, per-tool policy (MCP-*, INTEG-*, AE-3.6)

Filled in from the reservation stub the sprint chained up front; `down_revision` is
untouched. Adds `mcp_servers` and `integrations` (connection detail in the clear, secrets
in the sealed `*_enc` columns) plus `external_tool_policies`, the per-tool enable/trust
record that stays unencrypted because it is operator policy, not content.

Revision ID: 5a03ext0003
Revises: 5a02cal0002
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a03ext0003'
down_revision: Union[str, Sequence[str], None] = '5a02cal0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_tool_policies',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('trusted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_kind', 'source_id', 'tool_name', name='uq_external_tool_policy_scope')
    )
    with op.batch_alter_table('external_tool_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_tool_policies_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_tool_policies_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_tool_policies_source_kind'), ['source_kind'], unique=False)

    op.create_table('integrations',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('preset', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('credentials_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_integrations_owner_name'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_integrations_owner_slug')
    )
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrations_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_integrations_preset'), ['preset'], unique=False)

    op.create_table('mcp_servers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('transport', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('command', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('args_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('env_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('auth_required', sa.Boolean(), nullable=False),
    sa.Column('auth_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(), nullable=True),
    sa.Column('tools_json', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_mcp_servers_owner_name'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_mcp_servers_owner_slug')
    )
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_servers_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_mcp_servers_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcp_servers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_servers_owner_id'))
        batch_op.drop_index(batch_op.f('ix_mcp_servers_name'))

    op.drop_table('mcp_servers')
    with op.batch_alter_table('integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrations_preset'))
        batch_op.drop_index(batch_op.f('ix_integrations_owner_id'))
        batch_op.drop_index(batch_op.f('ix_integrations_name'))

    op.drop_table('integrations')
    with op.batch_alter_table('external_tool_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_tool_policies_source_kind'))
        batch_op.drop_index(batch_op.f('ix_external_tool_policies_source_id'))
        batch_op.drop_index(batch_op.f('ix_external_tool_policies_owner_id'))

    op.drop_table('external_tool_policies')
    # ### end Alembic commands ###
