"""reserved — external tool schema (sprint track T3: MCP + integrations)

A reservation stub; see `5a01mail0001` for why the chain is reserved up front. The external
tools track fills in only this file's body and never touches `down_revision`.

Revision ID: 5a03ext0003
Revises: 5a02cal0002
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a03ext0003'
down_revision: Union[str, Sequence[str], None] = '5a02cal0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — filled in by the external tools track (T3)."""
    pass


def downgrade() -> None:
    """Downgrade schema — filled in by the external tools track (T3)."""
    pass
