"""secret vault schema (sprint track T4: vault + backup)

Filled in from the reservation stub; see `5a01mail0001` for why the chain is reserved up
front. Only this file's body was written — `down_revision` is untouched.

Note this is the **user-facing secrets manager** (`VAULT-*`), not `core/vault` — that one is
the password-derived at-rest key custody and has no schema of its own.

Revision ID: 5a04vlt0004
Revises: 5a03ext0003
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a04vlt0004'
down_revision: Union[str, Sequence[str], None] = '5a03ext0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_entries',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secret_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_secret_entries_owner_id'), ['owner_id'], unique=False)

    op.create_table('secret_vault_config',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kek_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wrapped_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', name='uq_secret_vault_config_owner')
    )
    with op.batch_alter_table('secret_vault_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secret_vault_config_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('secret_vault_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_vault_config_owner_id'))

    op.drop_table('secret_vault_config')
    with op.batch_alter_table('secret_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secret_entries_owner_id'))
        batch_op.drop_index(batch_op.f('ix_secret_entries_created_at'))

    op.drop_table('secret_entries')
    # ### end Alembic commands ###
