"""reserved — secret vault schema (sprint track T4: vault + backup)

A reservation stub; see `5a01mail0001` for why the chain is reserved up front. The
vault/backup track fills in only this file's body and never touches `down_revision`.

Note this is the **user-facing secrets manager** (`VAULT-*`), not `core/vault` — that one is
the password-derived at-rest key custody and has no schema of its own.

Revision ID: 5a04vlt0004
Revises: 5a03ext0003
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a04vlt0004'
down_revision: Union[str, Sequence[str], None] = '5a03ext0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — filled in by the vault/backup track (T4)."""
    pass


def downgrade() -> None:
    """Downgrade schema — filled in by the vault/backup track (T4)."""
    pass
