"""document suggestion schema (DOC-3)

Suggestion sets + their individual anchored changes — a proposed change that has not been
applied, which is what `document_versions` (already-happened changes) cannot express.

The revision id/filename were reserved up front; see `5a01mail0001` for why the chain is
reserved ahead of the tracks that fill it in.

Revision ID: 5a05doc0005
Revises: 5a04vlt0004
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a05doc0005'
down_revision: Union[str, Sequence[str], None] = '5a04vlt0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table('document_suggestion_sets',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_suggestion_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_suggestion_sets_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_sets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_sets_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_sets_owner_id'), ['owner_id'], unique=False)

    op.create_table('document_suggestion_changes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('old_text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('new_text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('explanation_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_suggestion_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_suggestion_changes_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_changes_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_changes_set_id'), ['set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_suggestion_changes_status'), ['status'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('document_suggestion_changes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_suggestion_changes_status'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_changes_set_id'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_changes_owner_id'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_changes_document_id'))

    op.drop_table('document_suggestion_changes')
    with op.batch_alter_table('document_suggestion_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_suggestion_sets_owner_id'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_sets_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_sets_created_at'))
        batch_op.drop_index(batch_op.f('ix_document_suggestion_sets_conversation_id'))

    op.drop_table('document_suggestion_sets')
