"""reserved — document suggestion schema (sprint track T5: DOC-3)

A reservation stub; see `5a01mail0001` for why the chain is reserved up front. The doc assist
track fills in only this file's body and never touches `down_revision`.

Revision ID: 5a05doc0005
Revises: 5a04vlt0004
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a05doc0005'
down_revision: Union[str, Sequence[str], None] = '5a04vlt0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — filled in by the doc assist track (T5)."""
    pass


def downgrade() -> None:
    """Downgrade schema — filled in by the doc assist track (T5)."""
    pass
