"""reserved — API token schema (sprint track T6: AUTH-4)

A reservation stub; see `5a01mail0001` for why the chain is reserved up front. The platform
track fills in only this file's body and never touches `down_revision`. This is the tail of
the reserved chain — the next real migration after the sprint revises `5a06tok0006`.

Note these are **inbound** scoped access tokens (`AUTH-4`), distinct from
`service_credentials`, which holds the outbound third-party API keys.

Revision ID: 5a06tok0006
Revises: 5a05doc0005
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a06tok0006'
down_revision: Union[str, Sequence[str], None] = '5a05doc0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema — filled in by the platform track (T6)."""
    pass


def downgrade() -> None:
    """Downgrade schema — filled in by the platform track (T6)."""
    pass
