"""sealed the conversation title and the corpus source path (XC-SEC-3)

Both were stored in the clear. This adds their sealed columns and makes the legacy
cleartext columns nullable — it deliberately does **not** encrypt the existing values,
because it cannot: `core/db.init_db` upgrades to head at startup, before any login, so
this runs with the vault locked and no key in memory. The existing rows are sealed by the
lock-aware backfill in `app.py`, which waits for unlock and then drains the cleartext
columns to null. Reads tolerate both states meanwhile.

Downgrade drops the sealed columns. It cannot decrypt them back into the cleartext
columns for the same reason the upgrade cannot encrypt, so a sealed title/path does not
survive a downgrade — the honest behaviour for an at-rest column whose key is memory-only.

Revision ID: 5a07sec0007
Revises: 5a06tok0006
Create Date: 2026-08-13

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '5a07sec0007'
down_revision: Union[str, Sequence[str], None] = '5a06tok0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('conversations') as batch:
        batch.add_column(
            sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    with op.batch_alter_table('corpus_source') as batch:
        batch.add_column(
            sa.Column('path_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        # Nullable so the backfill can drop the cleartext once it is sealed, and so a
        # row written after this point carries no plaintext path at all.
        batch.alter_column(
            'path', existing_type=sa.VARCHAR(), nullable=True
        )


def downgrade() -> None:
    # Any row whose path was already sealed has a null cleartext `path`, so restoring the
    # NOT NULL constraint would fail on exactly the rows this feature created. Backfill an
    # empty string first: the value is unrecoverable either way, and this keeps the
    # downgrade from erroring instead of completing.
    op.execute("UPDATE corpus_source SET path = '' WHERE path IS NULL")
    with op.batch_alter_table('corpus_source') as batch:
        batch.alter_column('path', existing_type=sa.VARCHAR(), nullable=False)
        batch.drop_column('path_enc')

    with op.batch_alter_table('conversations') as batch:
        batch.drop_column('title_enc')
