"""snapshot preview descriptor

Revision ID: 6c91a1699b1b
Revises: 134f7d775645
Create Date: 2026-06-27 18:49:13.598244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6c91a1699b1b'
down_revision: Union[str, Sequence[str], None] = '134f7d775645'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preview_artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('preview_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.drop_column('preview_kind')
        batch_op.drop_column('preview_artifact_id')

    # ### end Alembic commands ###
