"""operator workflows

Revision ID: 6ff96c574e3b
Revises: e1b7c0a3f52d
Create Date: 2026-09-14 22:09:50.003717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6ff96c574e3b'
down_revision: Union[str, Sequence[str], None] = 'e1b7c0a3f52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commands',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('argument_hint_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_commands_owner_name')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commands_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_updated_at'))
        batch_op.drop_index(batch_op.f('ix_commands_owner_id'))
        batch_op.drop_index(batch_op.f('ix_commands_name'))
        batch_op.drop_index(batch_op.f('ix_commands_enabled'))
        batch_op.drop_index(batch_op.f('ix_commands_created_at'))

    op.drop_table('commands')
    # ### end Alembic commands ###
