"""add corpus

Revision ID: 705e12931a0d
Revises: b3ab8395802e
Create Date: 2026-06-17 20:53:36.619164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '705e12931a0d'
down_revision: Union[str, Sequence[str], None] = 'b3ab8395802e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpus_chunk',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source_id', 'content_hash')
    )
    with op.batch_alter_table('corpus_chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_chunk_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_chunk_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_chunk_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_corpus_chunk_source_kind'), ['source_kind'], unique=False)

    op.create_table('corpus_source',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_hint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corpus_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corpus_source_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('corpus_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_source_owner_id'))

    op.drop_table('corpus_source')
    with op.batch_alter_table('corpus_chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_chunk_source_kind'))
        batch_op.drop_index(batch_op.f('ix_corpus_chunk_source_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_chunk_owner_id'))
        batch_op.drop_index(batch_op.f('ix_corpus_chunk_content_hash'))

    op.drop_table('corpus_chunk')
    # ### end Alembic commands ###
