"""Added projects and the project scope column

Revision ID: 73a8a1da69b3
Revises: a2f60d9b4c31
Create Date: 2026-08-25 22:21:35.238581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '73a8a1da69b3'
down_revision: Union[str, Sequence[str], None] = 'a2f60d9b4c31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Every `project_id` is nullable and carries no server_default, deliberately: null
    # means *unfiled*, which is a real and permanent state, not a backfill placeholder.
    # Unfiled rows stay visible under every project scope, so this migration cannot hide
    # anything the operator already has — activating their first project adds to what
    # they see rather than subtracting from it.
    op.create_table('projects',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('root_path_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('git_initialized', sa.Boolean(), nullable=False),
    sa.Column('base_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_last_opened_at'), ['last_opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_conversations_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('corpus_source', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_corpus_source_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_research_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('corpus_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corpus_source_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_project_id'))
        batch_op.drop_column('project_id')

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_projects_last_opened_at'))

    op.drop_table('projects')
    # ### end Alembic commands ###
