"""gallery albums and upload favorite

Revision ID: 76afcd0f1019
Revises: 099b0b3b4145
Create Date: 2026-06-25 22:34:27.785095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '76afcd0f1019'
down_revision: Union[str, Sequence[str], None] = '099b0b3b4145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_albums',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery_albums', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_albums_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_albums_owner_id'), ['owner_id'], unique=False)

    op.create_table('gallery_album_items',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('upload_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'upload_id', name='uq_gallery_album_item')
    )
    with op.batch_alter_table('gallery_album_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_album_items_album_id'), ['album_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_album_items_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_album_items_upload_id'), ['upload_id'], unique=False)

    with op.batch_alter_table('uploads', schema=None) as batch_op:
        # Existing uploads default to not-favorited; server_default lets the NOT NULL add
        # succeed on a populated table (mirrors the messages.pinned migration).
        batch_op.add_column(
            sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_column('favorite')

    with op.batch_alter_table('gallery_album_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_album_items_upload_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_album_items_owner_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_album_items_album_id'))

    op.drop_table('gallery_album_items')
    with op.batch_alter_table('gallery_albums', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_albums_owner_id'))
        batch_op.drop_index(batch_op.f('ix_gallery_albums_created_at'))

    op.drop_table('gallery_albums')
    # ### end Alembic commands ###
