"""Added the conversation permission level

Revision ID: 76cf84ae88af
Revises: d2b6f9c48ae1
Create Date: 2026-08-30 18:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '76cf84ae88af'
down_revision: Union[str, Sequence[str], None] = 'd2b6f9c48ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The second axis of a thread: how far the model may go on its own. Not nullable and
    # defaulted to `edit`, which is what every existing thread has effectively been
    # running at — workspace writes pass, and host, external and outbound effects wait for
    # the operator — so the rows already on disk keep behaving as they did rather than
    # waking up read-only or unattended.
    #
    # The server default is what carries that to rows an older writer inserts (a backup
    # restore), for the same reason the mode rename moved its default with its values.
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'permission_level',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='edit',
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('permission_level')
