"""add keeper bookmark to snapshots and document versions

Revision ID: 775d4d4c9043
Revises: fc7e82f05462
Create Date: 2026-07-14 21:17:58.865570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '775d4d4c9043'
down_revision: Union[str, Sequence[str], None] = 'fc7e82f05462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        # Existing versions default to not-kept; server_default lets the NOT NULL add
        # succeed on a populated table (mirrors the messages.pinned migration).
        batch_op.add_column(
            sa.Column('keeper', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_document_versions_keeper'), ['keeper'], unique=False)

    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('keeper', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.create_index(batch_op.f('ix_workspace_snapshots_keeper'), ['keeper'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_snapshots_keeper'))
        batch_op.drop_column('keeper')

    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_versions_keeper'))
        batch_op.drop_column('keeper')

    # ### end Alembic commands ###
