"""Added claim-level attribution rows

Revision ID: 794756b78aa8
Revises: a7c31e9b5d04
Create Date: 2026-09-20 14:14:51.048934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '794756b78aa8'
down_revision: Union[str, Sequence[str], None] = 'a7c31e9b5d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A citation on a message says *that* a page was read; it never said which sentence
    # in it carried the claim, which is the thing an operator opens a citation to check.
    # A second reader now runs after a research answer and reads the finished prose back
    # against the sources the turn retained, and this is where its claim -> source ->
    # passage triples live: one sealed row per assistant turn, keyed by the branch node
    # every operator surface already addresses a turn by.
    #
    # Nothing backfills. The pass is retroactive by re-running rather than by migration —
    # tool results are persisted structurally, so a thread that finished before this
    # landed can be read at any time, and doing that here would mean a schema upgrade
    # spending a model call per answer with the vault still locked.
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_attributions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('claims_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_attributions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_attributions_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attributions_extracted_at'), ['extracted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_attributions_message_id'), ['message_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_message_attributions_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_attributions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_attributions_owner_id'))
        batch_op.drop_index(batch_op.f('ix_message_attributions_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_attributions_extracted_at'))
        batch_op.drop_index(batch_op.f('ix_message_attributions_conversation_id'))

    op.drop_table('message_attributions')
    # ### end Alembic commands ###
