"""uploads

Revision ID: 7d06dac74ae5
Revises: 66463d56be0c
Create Date: 2026-06-18 19:59:30.592164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '7d06dac74ae5'
down_revision: Union[str, Sequence[str], None] = '66463d56be0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploads',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('filename_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('blob_enc', sa.LargeBinary(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('has_text', sa.Boolean(), nullable=False),
    sa.Column('vision', sa.Boolean(), nullable=False),
    sa.Column('extractor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sha256', name='uq_uploads_owner_sha256')
    )
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_uploads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_uploads_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uploads_status'))
        batch_op.drop_index(batch_op.f('ix_uploads_owner_id'))
        batch_op.drop_index(batch_op.f('ix_uploads_created_at'))

    op.drop_table('uploads')
    # ### end Alembic commands ###
