"""merged the egress-grant and scoped-approval-grant heads

Revision ID: 82cdb76f67d8
Revises: c7e2a91f0d34, c9a4e07b31d5
Create Date: 2026-09-07 09:22:56.517453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '82cdb76f67d8'
down_revision: Union[str, Sequence[str], None] = ('c7e2a91f0d34', 'c9a4e07b31d5')
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    pass


def downgrade() -> None:
    """Downgrade schema."""
    pass
