"""Added conversation auto-compaction checkpoints

Revision ID: 8a530111213d
Revises: 2f9c81ad4e07
Create Date: 2026-08-18 22:00:47.822720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '8a530111213d'
down_revision: Union[str, Sequence[str], None] = '2f9c81ad4e07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_compact_override', sa.Boolean(), nullable=True))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        # server_default backfills existing rows (a NOT NULL add needs one) — every
        # message written before this revision predates compaction, so none is a
        # checkpoint. `compacted_through` stays nullable: only a checkpoint sets it.
        batch_op.add_column(
            sa.Column('compacted', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(sa.Column('compacted_through', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('compacted_through')
        batch_op.drop_column('compacted')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('auto_compact_override')

    # ### end Alembic commands ###
