"""added managed_models table

Revision ID: 95fd6a9dedf2
Revises: 3c89e0787781
Create Date: 2026-06-21 12:53:39.661685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '95fd6a9dedf2'
down_revision: Union[str, Sequence[str], None] = '3c89e0787781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('managed_models',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hf_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artifact_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_models_endpoint_id'), ['endpoint_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_managed_models_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managed_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_models_owner_id'))
        batch_op.drop_index(batch_op.f('ix_managed_models_endpoint_id'))

    op.drop_table('managed_models')
    # ### end Alembic commands ###
