"""add search providers

Revision ID: 9c3c293f5100
Revises: db79d55f0aa1
Create Date: 2026-06-13 00:19:15.185786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9c3c293f5100'
down_revision: Union[str, Sequence[str], None] = 'db79d55f0aa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_providers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('engines', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_search_provider_owner_name')
    )
    with op.batch_alter_table('search_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_providers_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_providers_owner_id'))

    op.drop_table('search_providers')
    # ### end Alembic commands ###
