"""conversation ephemeral flag

Revision ID: a1c4e7b9d203
Revises: e6b7252fc39a
Create Date: 2026-06-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a1c4e7b9d203'
down_revision: Union[str, Sequence[str], None] = 'e6b7252fc39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adding a column is the one ALTER SQLite supports natively, so we issue a plain
    ``ADD COLUMN`` rather than the env's batch mode. Batch mode rebuilds the table
    through a ``_alembic_tmp_conversations`` copy; if that run is interrupted the
    temp table is stranded and every later attempt then dies on
    "table _alembic_tmp_conversations already exists". The native add avoids the
    rebuild entirely, and the defensive drop below clears any orphan temp table a
    prior batch attempt of this migration left behind so a stuck DB recovers.
    """
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_conversations")
    # Existing conversations are real (non-scratch); server_default lets the
    # NOT NULL add succeed on a populated table.
    op.add_column(
        "conversations",
        sa.Column("ephemeral", sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column("conversations", "ephemeral")
