"""Added the conversation work summary

Revision ID: a1d47c6b9e20
Revises: 794756b78aa8
Create Date: 2026-09-20 10:12:04.118273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a1d47c6b9e20'
down_revision: Union[str, Sequence[str], None] = '794756b78aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Both columns are new, so there is nothing to backfill and no cleartext twin to
    # seal later: every row starts null, meaning "never summarized", which is exactly
    # what the sweeper's staleness rule reads as a candidate.
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_summary_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('work_summary_at', sa.DateTime(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('work_summary_at')
        batch_op.drop_column('work_summary_enc')
