"""Added the per-conversation agent plan

Revision ID: ac1d7f83996a
Revises: 8a530111213d
Create Date: 2026-08-18 23:07:14.677916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ac1d7f83996a'
down_revision: Union[str, Sequence[str], None] = '8a530111213d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('items_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_plans_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_plans_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_plans_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_plans_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_conversation_id'))

    op.drop_table('conversation_plans')
    # ### end Alembic commands ###
