"""Widened the corpus chunk dedup key to the item it came from

Revision ID: b3d9c41f7a12
Revises: ac1d7f83996a
Create Date: 2026-08-20 00:00:00.000000

The old key was (owner_id, source_id, content_hash), which reads "one copy of any given
content per source". That is right for a source that *is* one item (a document, an upload)
and wrong for one that holds many: a folder crawl indexes a whole tree under a single
source, so two byte-identical files in it — a repeated LICENSE, two empty ``__init__.py``,
one config copied into two environments — collided, and only whichever path the crawl
reached first could be stored. The other was never indexed at all.

``external_ref`` joins the key, which identifies the item. The new constraint is strictly
weaker, so every existing row already satisfies it and nothing needs backfilling.

SQLite cannot alter a constraint in place, and the constraint being replaced was created
unnamed (so it cannot be dropped by name either). Hence ``copy_from``: it hands batch mode
the table definition to rebuild from, and since that definition omits the old constraint,
the rebuilt table simply doesn't have it. Downgrading re-narrows the key and will fail, by
design, on a database that has since indexed two identical files — there is no correct way
to choose which of them to discard.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b3d9c41f7a12'
down_revision: Union[str, Sequence[str], None] = 'ac1d7f83996a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _corpus_chunk() -> sa.Table:
    """The table as it stands, minus its unique constraint — the shape batch mode rebuilds
    from. Spelled out rather than reflected or imported from ``models``: reflection can't
    round-trip an unnamed SQLite constraint, and a migration that read the live model would
    change meaning the next time that model does.

    The indexes are part of that shape and must be listed. A rebuild recreates exactly
    what this definition declares, so an index left out here is an index silently dropped
    — including ``kb_excluded``, which every ambient recall scan filters on."""
    return sa.Table(
        'corpus_chunk',
        sa.MetaData(),
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('external_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ordinal', sa.Integer(), nullable=False),
        sa.Column('text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('embedding_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('embedding_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('embedding_dim', sa.Integer(), nullable=True),
        sa.Column(
            'kb_excluded', sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('ix_corpus_chunk_content_hash', 'content_hash'),
        sa.Index('ix_corpus_chunk_kb_excluded', 'kb_excluded'),
        sa.Index('ix_corpus_chunk_owner_id', 'owner_id'),
        sa.Index('ix_corpus_chunk_source_id', 'source_id'),
        sa.Index('ix_corpus_chunk_source_kind', 'source_kind'),
    )


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table(
        'corpus_chunk', schema=None, copy_from=_corpus_chunk(), recreate='always'
    ) as batch_op:
        batch_op.create_unique_constraint(
            'uq_corpus_chunk_ref_content',
            ['owner_id', 'source_id', 'external_ref', 'content_hash'],
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table(
        'corpus_chunk', schema=None, copy_from=_corpus_chunk(), recreate='always'
    ) as batch_op:
        # Named, unlike the constraint this replaced: batch mode refuses an anonymous one,
        # and the name is immaterial to a downgrade — the column list is the behaviour.
        batch_op.create_unique_constraint(
            'uq_corpus_chunk_content', ['owner_id', 'source_id', 'content_hash']
        )
