"""Split the agent's task list from the plan it works to

The word "plan" named two things and implemented one. What the old `conversation_plans`
table held was the agent's running checklist, so it becomes `conversation_tasks`; the name
it vacates is taken by the thing that actually is a plan — the written document a Plan-level
turn submits for the operator to approve.

Three steps, in this order:
  1. rename `conversation_plans` -> `conversation_tasks` (and its indexes with it),
  2. create the new `conversation_plans` for the document,
  3. rewrite the operator's stored disabled-tool names, which are namespaced and so went
     stale the moment the category was renamed. Without this a tool the operator switched
     off silently switches back on, which is the one kind of stale value here that fails
     *open*.

Revision ID: b4e1c72af903
Revises: 82cdb76f67d8
Create Date: 2026-09-11 00:00:00.000000

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b4e1c72af903'
down_revision: Union[str, Sequence[str], None] = '82cdb76f67d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


#: Old namespaced tool name -> new one. The task-list tools moved category *and* shed the
#: harness's own wording (`tools/tasks.py` renames them on the way out).
_RENAMED_TOOLS = {
    "plan_write_plan": "tasks_write",
    "plan_update_task_statuses": "tasks_update_statuses",
    "plan_read_plan": "tasks_read",
}

_DISABLED_TOOLS_KEY = "tools.disabled"


def _remap_disabled_tools(mapping: dict[str, str]) -> None:
    """Rewrite every stored `tools.disabled` list through `mapping`.

    Read-modify-write per row rather than a SQL replace: the value is a JSON array, and a
    substring swap inside it would also hit a name that merely contains one of these.
    A row that will not parse is left exactly as it is — `services/tool_policy.py` already
    reads an unparseable value as "nothing disabled", and rewriting it here would be
    deciding on the operator's behalf what they had meant.
    """
    settings = sa.table(
        "app_settings",
        sa.column("id", sa.String),
        sa.column("key", sa.String),
        sa.column("value", sa.String),
    )
    connection = op.get_bind()
    rows = connection.execute(
        sa.select(settings.c.id, settings.c.value).where(settings.c.key == _DISABLED_TOOLS_KEY)
    ).fetchall()
    for row_id, raw in rows:
        try:
            names = json.loads(raw)
        except (TypeError, ValueError):
            continue
        if not isinstance(names, list):
            continue
        updated = sorted(
            {mapping.get(name, name) for name in names if isinstance(name, str) and name}
        )
        if updated != names:
            connection.execute(
                settings.update()
                .where(settings.c.id == row_id)
                .values(value=json.dumps(updated))
            )


def upgrade() -> None:
    """Upgrade schema."""
    # 1. The old table was always the task list. SQLite cannot rename an index in place,
    #    so each is dropped and recreated under the new prefix.
    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_plans_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_conversation_id'))

    op.rename_table('conversation_plans', 'conversation_tasks')

    with op.batch_alter_table('conversation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_tasks_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_tasks_updated_at'), ['updated_at'], unique=False)

    # 2. The name it vacated, for the document the operator approves.
    op.create_table('conversation_plans',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='pending'),
    sa.Column('revision', sa.Integer(), nullable=False, server_default='1'),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_plans_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_plans_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_plans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_plans_updated_at'), ['updated_at'], unique=False)

    # 3. The operator's own switched-off tools, under their new names.
    _remap_disabled_tools(_RENAMED_TOOLS)


def downgrade() -> None:
    """Downgrade schema."""
    _remap_disabled_tools({new: old for old, new in _RENAMED_TOOLS.items()})

    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_plans_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_status'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_plans_conversation_id'))

    op.drop_table('conversation_plans')

    with op.batch_alter_table('conversation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_tasks_updated_at'))
        batch_op.drop_index(batch_op.f('ix_conversation_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_tasks_conversation_id'))

    op.rename_table('conversation_tasks', 'conversation_plans')

    with op.batch_alter_table('conversation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_plans_conversation_id'), ['conversation_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_conversation_plans_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_plans_updated_at'), ['updated_at'], unique=False)
