"""Dropped the research entity

Revision ID: b6d20a5c74e1
Revises: 76cf84ae88af
Create Date: 2026-08-30 20:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'b6d20a5c74e1'
down_revision: Union[str, Sequence[str], None] = '76cf84ae88af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Research stopped being an entity. It was a pipeline with its own row — a question,
    # a frozen plan, a finished report — driven by a Run and read back through its own
    # REST surface; it is now a *conversation in research mode*, which means the thread
    # itself is the record and `conversations`/`messages` already store it.
    #
    # The table goes rather than being left behind, because a schema that still describes
    # the old shape is the thing a future reader trusts. What it held is not silently
    # lost: nothing migrates a finished report into a conversation (a report is not a
    # transcript, and inventing turns that were never taken would be worse than losing
    # the row), so this is a deliberate one-way drop of a retired feature's storage.
    #
    # `notifications.research_id` deliberately stays: it is nullable, nothing writes it
    # any more, and dropping it would rewrite the table to gain nothing.
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_status'))
        batch_op.drop_index(batch_op.f('ix_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_project_id'))
        batch_op.drop_index(batch_op.f('ix_research_owner_id'))
        batch_op.drop_index(batch_op.f('ix_research_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_conversation_id'))

    op.drop_table('research')


def downgrade() -> None:
    """Downgrade schema."""
    # The table comes back empty, which is the honest reverse: the rows it held were
    # dropped, and a downgrade cannot conjure them. Recreated in full so an older build
    # that still queries it finds the shape it expects rather than a missing relation.
    op.create_table('research',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('question_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clarifying_questions_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_status'), ['status'], unique=False)
