"""dropped documents and gallery

The Documents library (with the agent's authoring tools) and the Gallery were removed
from the product. Their tables shipped, so their creating migrations stay exactly as
they are — history describes what a database that ran them actually contains, and
rewriting it would strand every existing database mid-chain. This one revision takes
the tables away at the head instead.

``uploads.favorite`` deliberately survives: the star is an upload property the uploads
surface still owns, and only its gallery framing went away. The migration that added it
(``76afcd0f1019``) therefore stays intact, and only its two gallery tables are dropped.

Revision ID: c0d5e9a41f37
Revises: a3c81f402e77
Create Date: 2026-08-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c0d5e9a41f37'
down_revision: Union[str, Sequence[str], None] = 'a3c81f402e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Children before parents: `gallery_album_items` carries FKs to `gallery_albums`
    # (and to `uploads`, which stays), and the suggestion changes hang off their set.
    op.drop_table('document_suggestion_changes')
    op.drop_table('document_suggestion_sets')
    op.drop_table('document_versions')
    op.drop_table('documents')
    op.drop_table('gallery_album_items')
    op.drop_table('gallery_albums')


def downgrade() -> None:
    """Downgrade schema.

    Re-creates the tables in the shape they had at this revision — the original
    columns plus everything the later migrations added (``documents.conversation_id``
    and ``.project_id``, ``document_versions.keeper``) — so stepping further down
    hands each earlier migration the schema it expects to unwind. The rows are gone
    for good; a downgrade restores the shape, not the data.
    """
    op.create_table(
        'documents',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('body_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('archived', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_documents_conversation_id'), ['conversation_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_documents_project_id'), ['project_id'], unique=False)

    op.create_table(
        'document_versions',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('body_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('doc_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('keeper', sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('document_versions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_document_versions_document_id'), ['document_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_document_versions_origin'), ['origin'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_document_versions_owner_id'), ['owner_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_document_versions_keeper'), ['keeper'], unique=False)

    op.create_table(
        'document_suggestion_sets',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('summary_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('document_suggestion_sets', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_sets_conversation_id'),
            ['conversation_id'],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_sets_created_at'), ['created_at'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_sets_document_id'), ['document_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_sets_owner_id'), ['owner_id'], unique=False
        )

    op.create_table(
        'document_suggestion_changes',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('set_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('document_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('ordinal', sa.Integer(), nullable=False),
        sa.Column('old_text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('new_text_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('explanation_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('decided_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('document_suggestion_changes', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_changes_document_id'), ['document_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_changes_owner_id'), ['owner_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_changes_set_id'), ['set_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_document_suggestion_changes_status'), ['status'], unique=False
        )

    op.create_table(
        'gallery_albums',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('gallery_albums', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gallery_albums_created_at'), ['created_at'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_gallery_albums_owner_id'), ['owner_id'], unique=False)

    op.create_table(
        'gallery_album_items',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('album_id', sa.String(), nullable=False),
        sa.Column('upload_id', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], ['gallery_albums.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['upload_id'], ['uploads.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('album_id', 'upload_id', name='uq_gallery_album_item'),
    )
    with op.batch_alter_table('gallery_album_items', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gallery_album_items_album_id'), ['album_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_gallery_album_items_owner_id'), ['owner_id'], unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_gallery_album_items_upload_id'), ['upload_id'], unique=False
        )
