"""add service credentials

Revision ID: c4152271944a
Revises: fbbd26622564
Create Date: 2026-06-17 18:48:32.237501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c4152271944a'
down_revision: Union[str, Sequence[str], None] = 'fbbd26622564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_credentials',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('service', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('api_key_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'service', name='uq_service_credential_owner_service')
    )
    with op.batch_alter_table('service_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_credentials_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_credentials_owner_id'))

    op.drop_table('service_credentials')
    # ### end Alembic commands ###
