"""Added the conversation mode column

Revision ID: c4d1f7a90b62
Revises: 73a8a1da69b3
Create Date: 2026-08-25 23:40:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c4d1f7a90b62'
down_revision: Union[str, Sequence[str], None] = '73a8a1da69b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # NOT NULL with a server_default here, unlike `project_id`: every existing thread is
    # a chat thread, and "no mode" is not a state the code can act on — the resolver has
    # to answer sandbox-or-worktree for every run. The default stays on the column so a
    # row inserted by anything that predates the model (a backup restore) is still valid.
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'mode',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='chat',
            )
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('mode')
