"""added egress grants

Revision ID: c7e2a91f0d34
Revises: b6d20a5c74e1
Create Date: 2026-09-03 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c7e2a91f0d34'
down_revision: Union[str, Sequence[str], None] = 'b6d20a5c74e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('egress_grants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'conversation_id', 'domain', name='uq_egress_grant_scope')
    )
    with op.batch_alter_table('egress_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_egress_grants_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_egress_grants_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('egress_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_egress_grants_owner_id'))
        batch_op.drop_index(batch_op.f('ix_egress_grants_conversation_id'))

    op.drop_table('egress_grants')
    # ### end Alembic commands ###
