"""Sealed the artifact title and filename

Revision ID: c8e41a5b2f07
Revises: b3d9c41f7a12
Create Date: 2026-08-20 00:00:00.000000

An artifact's bytes were already encrypted at rest, but its ``title`` and ``filename``
were not — and a filename is content, not routing metadata: ``q3-layoffs-draft.html``
says as much about the operator as the document it names. Every peer entity seals its
equivalent, so these two join them (`XC-SEC-3`).

This migration only makes room. It **cannot do the sealing itself**: ``init_db`` upgrades
to head at startup, before any login, so there is no key here. It adds the two ``_enc``
columns and relaxes the legacy pair to nullable; the startup backfill in ``app.py`` seals
the surviving cleartext once the vault is unlocked, and ``services/sealing.open_sealed``
reads correctly from either state in the meantime. That is the same shape the conversation
title and the corpus source path already converted under.

Downgrading drops the sealed columns. Any row already healed by the backfill has had its
cleartext nulled, so its title and filename are lost on the way down — recoverable only
from a backup. The legacy columns therefore stay nullable in the downgrade: re-imposing
NOT NULL would fail outright on exactly those rows.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c8e41a5b2f07'
down_revision: Union[str, Sequence[str], None] = 'b3d9c41f7a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('filename_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )
        # Nullable because the backfill nulls each value as it seals it. Until then the
        # old rows still answer reads from here.
        batch_op.alter_column(
            'title', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=True
        )
        batch_op.alter_column(
            'filename', existing_type=sqlmodel.sql.sqltypes.AutoString(), nullable=True
        )


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_column('filename_enc')
        batch_op.drop_column('title_enc')
