"""Scoped approval grants to a command prefix

Revision ID: c9a4e07b31d5
Revises: b6d20a5c74e1
Create Date: 2026-09-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c9a4e07b31d5'
down_revision: Union[str, Sequence[str], None] = 'b6d20a5c74e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A grant on a tool that runs a command now names the command, so one "allow for this
    # conversation" on a shell tool stops meaning every command the thread will ever run.
    #
    # The column is NOT NULL with an empty default rather than nullable, and that is the
    # load-bearing part: SQLite treats NULLs as distinct inside a UNIQUE index, so a NULL
    # prefix would make the re-grant upsert's ON CONFLICT never match and every refresh of
    # a whole-tool grant would insert another row instead of moving its expiry. Existing
    # rows take `''` — the whole-tool scope they were granted under.
    with op.batch_alter_table('approval_grants', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'command_prefix',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='',
            )
        )
        batch_op.drop_constraint('uq_approval_grant_scope', type_='unique')
        batch_op.create_unique_constraint(
            'uq_approval_grant_scope',
            ['owner_id', 'conversation_id', 'tool_name', 'command_prefix'],
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Narrower grants cannot survive a column that cannot hold them: a command-scoped row
    # would come back as a grant over the whole tool, which is wider than anything the
    # operator agreed to. They are dropped instead, so the older code asks again.
    op.execute(sa.text("DELETE FROM approval_grants WHERE command_prefix != ''"))
    with op.batch_alter_table('approval_grants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_approval_grant_scope', type_='unique')
        batch_op.create_unique_constraint(
            'uq_approval_grant_scope', ['owner_id', 'conversation_id', 'tool_name']
        )
        batch_op.drop_column('command_prefix')
