"""added scheduled tasks and task runs

Revision ID: cc7ca4be223e
Revises: 980b3b3eeffb
Create Date: 2026-07-11 22:36:19.657332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'cc7ca4be223e'
down_revision: Union[str, Sequence[str], None] = '980b3b3eeffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('schedule_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_at', sa.DateTime(), nullable=True),
    sa.Column('every_seconds', sa.Float(), nullable=True),
    sa.Column('cron_expr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('output', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pre_authorized', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('webhook_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_schedule_type'), ['schedule_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_webhook_token'), ['webhook_token'], unique=True)

    op.create_table('task_runs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_runs_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_runs_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_runs_task_id'))
        batch_op.drop_index(batch_op.f('ix_task_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_task_runs_run_id'))
        batch_op.drop_index(batch_op.f('ix_task_runs_conversation_id'))

    op.drop_table('task_runs')
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_webhook_token'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_schedule_type'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_owner_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_kind'))
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_enabled'))

    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
