"""Renamed the conversation modes

Revision ID: d2b6f9c48ae1
Revises: a1f39d47c2be
Create Date: 2026-08-30 10:15:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd2b6f9c48ae1'
down_revision: Union[str, Sequence[str], None] = 'a1f39d47c2be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The mode is no longer a binary. It names a *kind of work* — normal, research, code —
    # and the registry that owns what each implies is keyed by those names, so the stored
    # vocabulary moves with it rather than being translated at every read. Keeping the old
    # words in the column while the code and the operator's screen say the new ones is the
    # split this rename exists to avoid.
    #
    # A data-only migration: same column, same type, same nullability. Rows carrying
    # anything else are left alone — the registry resolves an unrecognised value to the
    # mode that reaches the least, so an unknown row degrades rather than breaking.
    op.execute(sa.text("UPDATE conversations SET mode = 'normal' WHERE mode = 'chat'"))
    op.execute(sa.text("UPDATE conversations SET mode = 'code' WHERE mode = 'coding'"))
    # The server default moves with the values, so a row inserted by something that
    # predates the model (a backup restore) is still a mode the registry knows.
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column(
            'mode',
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            server_default='normal',
        )


def downgrade() -> None:
    """Downgrade schema."""
    # Research has no pre-rename equivalent: it is a sandbox thread like `chat` was, and
    # that is the honest downgrade — it loses the distinction rather than leaving a value
    # the older code has no branch for.
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.alter_column(
            'mode',
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
            server_default='chat',
        )
    op.execute(sa.text("UPDATE conversations SET mode = 'coding' WHERE mode = 'code'"))
    op.execute(
        sa.text("UPDATE conversations SET mode = 'chat' WHERE mode IN ('normal', 'research')")
    )
