"""Made endpoint model optional

Revision ID: d8f9871c9589
Revises: 5fec837f8026
Create Date: 2026-06-11 20:00:41.995044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'd8f9871c9589'
down_revision: Union[str, Sequence[str], None] = '5fec837f8026'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.alter_column('model',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
