"""message pin flag

Revision ID: db79d55f0aa1
Revises: 4ef3ed2e19d2
Create Date: 2026-06-11 23:25:06.813681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'db79d55f0aa1'
down_revision: Union[str, Sequence[str], None] = '4ef3ed2e19d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        # Existing rows default to unpinned; server_default lets the NOT NULL add
        # succeed on a populated table.
        batch_op.add_column(
            sa.Column('pinned', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('pinned')

    # ### end Alembic commands ###
