"""subagent register

Revision ID: dd362eb90fd7
Revises: b4e1c72af903
Create Date: 2026-09-12 10:08:51.254207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'dd362eb90fd7'
down_revision: Union[str, Sequence[str], None] = 'b4e1c72af903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subagent_records',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('child_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('spec_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_policy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('delegation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_used', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subagent_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subagent_records_child_conversation_id'), ['child_conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subagent_records_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subagent_records_parent_conversation_id'), ['parent_conversation_id'], unique=False)
        # Every run that ends asks this table whether it was a sub-agent, so this lookup
        # runs once per run in the process — ordinary chat turns included.
        batch_op.create_index(batch_op.f('ix_subagent_records_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subagent_records_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subagent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subagent_records_status'))
        batch_op.drop_index(batch_op.f('ix_subagent_records_run_id'))
        batch_op.drop_index(batch_op.f('ix_subagent_records_parent_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_subagent_records_owner_id'))
        batch_op.drop_index(batch_op.f('ix_subagent_records_child_conversation_id'))

    op.drop_table('subagent_records')
    # ### end Alembic commands ###
