"""subagent handle

Revision ID: e1b7c0a3f52d
Revises: dd362eb90fd7
Create Date: 2026-09-12 12:41:07.113904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e1b7c0a3f52d'
down_revision: Union[str, Sequence[str], None] = 'dd362eb90fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('subagent_records', schema=None) as batch_op:
        # A server default rather than a nullable column: the handle is the only name the
        # model has for a sub-agent, and a null one would have to be handled by every
        # reader forever. Empty is a state the launcher already knows what to do with.
        batch_op.add_column(
            sa.Column(
                'handle',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='',
            )
        )
        # Every read of a handle is "this parent thread's sub-agent called X" — the
        # launcher's uniqueness check, and both of the tools that address one.
        batch_op.create_index(
            batch_op.f('ix_subagent_records_handle'), ['handle'], unique=False
        )

    # Backfill, so the cards a running installation already has stay *addressable* and not
    # merely visible. A row that predates handles has exactly one name anybody ever saw it
    # by — its spec's — which is also what the launcher falls back to for a launch that
    # names no handle, so this is the existing rule applied to history rather than a second
    # one invented for it.
    op.execute("UPDATE subagent_records SET handle = spec_name WHERE handle = ''")


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('subagent_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subagent_records_handle'))
        batch_op.drop_column('handle')
