"""dropped local model serving

Odysseus works off **endpoints** — OpenAI-compatible URLs the operator points it at. It no
longer downloads weights, installs inference engines, or supervises a local model server,
so the schema that tracked those servers goes away: the `managed_models` table, and the
two endpoint columns that existed only to describe a server this process owned
(`managed`, and the process liveness in `live_status`).

The migrations that created them stay exactly as they are — history describes what a
database that ran them actually contains, and rewriting it would strand every existing
database mid-chain. In particular ``fd15ea21e8dd`` also added ``provider``, which stays.

What was a `local` provider is folded back into `openai-compatible`. The two were always
wire-identical; `local` existed only so the surfaces could tell "a server I pointed at"
from "a model this app serves", and the second half of that distinction no longer exists.
Left alone, those rows would name an adapter that isn't registered any more and fail
resolution outright — so the endpoint survives the change, pointing at whatever is still
listening on the URL it already had.

Revision ID: e41b7c95d0a3
Revises: c0d5e9a41f37
Create Date: 2026-08-29 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e41b7c95d0a3'
down_revision: Union[str, Sequence[str], None] = 'c0d5e9a41f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The table first: it carries an FK into `model_endpoints`, and dropping it here means
    # the endpoint rebuild below has no dependant left to reason about.
    op.drop_table('managed_models')

    # A row that was stopped when the app last ran is not a row the operator disabled —
    # `enabled` is their switch alone now, so hand it back on rather than leaving an
    # endpoint silently benched by a serving layer that no longer exists.
    op.execute("UPDATE model_endpoints SET enabled = 1 WHERE managed = 1")
    op.execute(
        "UPDATE model_endpoints SET provider = 'openai-compatible' WHERE provider = 'local'"
    )

    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.drop_column('live_status')
        batch_op.drop_column('managed')


def downgrade() -> None:
    """Downgrade schema.

    Restores the shape at this revision — the endpoint columns, and `managed_models` with
    every column the three migrations that built it added (`launch_options`, `source`) —
    so stepping further down hands each earlier migration the schema it expects to unwind.
    The rows are gone for good; a downgrade restores the shape, not the data, and nothing
    can recover which endpoints this process used to serve.
    """
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('managed', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('live_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    op.create_table(
        'managed_models',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('engine', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('workload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('hf_repo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('quant', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('artifact_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('port', sa.Integer(), nullable=True),
        sa.Column('pid', sa.Integer(), nullable=True),
        sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('launch_options', sa.JSON(), nullable=False, server_default='{}'),
        sa.Column('source', sa.String(), nullable=False, server_default='huggingface'),
        sa.ForeignKeyConstraint(
            ['endpoint_id'],
            ['model_endpoints.id'],
            name='fk_managed_models_endpoint_id',
            ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('managed_models', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_managed_models_endpoint_id'), ['endpoint_id'], unique=True
        )
        batch_op.create_index(
            batch_op.f('ix_managed_models_owner_id'), ['owner_id'], unique=False
        )
