"""Added denormalized last-used model to conversations

Revision ID: e6b7252fc39a
Revises: 9c3c293f5100
Create Date: 2026-06-14 10:05:32.776773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'e6b7252fc39a'
down_revision: Union[str, Sequence[str], None] = '9c3c293f5100'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
