"""Added embedding-role model pin to ModelRole

Revision ID: fbbd26622564
Revises: d7fe6b708434
Create Date: 2026-06-17 00:24:03.031452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fbbd26622564'
down_revision: Union[str, Sequence[str], None] = 'd7fe6b708434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_roles', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
