"""added research runs and notification research link

Revision ID: fc7e82f05462
Revises: cc7ca4be223e
Create Date: 2026-07-12 01:04:23.472492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fc7e82f05462'
down_revision: Union[str, Sequence[str], None] = 'cc7ca4be223e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('question_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('clarifying_questions_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_enc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_status'), ['status'], unique=False)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.create_index(batch_op.f('ix_notifications_research_id'), ['research_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_research_id'))
        batch_op.drop_column('research_id')

    with op.batch_alter_table('research', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_status'))
        batch_op.drop_index(batch_op.f('ix_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_research_owner_id'))
        batch_op.drop_index(batch_op.f('ix_research_created_at'))
        batch_op.drop_index(batch_op.f('ix_research_conversation_id'))

    op.drop_table('research')
    # ### end Alembic commands ###
