"""endpoint provider kind and managed liveness

Revision ID: fd15ea21e8dd
Revises: 5a07sec0007
Create Date: 2026-08-15 10:47:45.652302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # autogenerated column types reference sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fd15ea21e8dd'
down_revision: Union[str, Sequence[str], None] = '5a07sec0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # A managed row whose endpoint was deleted before this FK existed would violate
    # it the moment the constraint lands — null the dangling references first.
    op.execute(
        "UPDATE managed_models SET endpoint_id = NULL "
        "WHERE endpoint_id IS NOT NULL "
        "AND endpoint_id NOT IN (SELECT id FROM model_endpoints)"
    )
    with op.batch_alter_table('managed_models', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_managed_models_endpoint_id',
            'model_endpoints',
            ['endpoint_id'],
            ['id'],
            ondelete='SET NULL',
        )

    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'provider',
                sqlmodel.sql.sqltypes.AutoString(),
                nullable=False,
                server_default='openai-compatible',
            )
        )
        batch_op.add_column(
            sa.Column('managed', sa.Boolean(), nullable=False, server_default=sa.false())
        )
        batch_op.add_column(
            sa.Column('live_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    # Backfill the serving-owned endpoints, until now recognizable only by the
    # "Local · " display-name prefix the serving layer stamps. Their old `enabled`
    # was process liveness (stop/crash/reconcile wrote False) — carry it into
    # `live_status` and hand `enabled` back to the operator as a switch that
    # defaults on.
    op.execute(
        "UPDATE model_endpoints SET provider = 'local', managed = 1, "
        "live_status = CASE WHEN enabled THEN 'running' ELSE 'stopped' END, "
        "enabled = 1 "
        "WHERE name LIKE 'Local · %'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Restore the legacy overloading: a managed endpoint's `enabled` meant liveness.
    op.execute(
        "UPDATE model_endpoints SET enabled = CASE WHEN live_status = 'running' "
        "THEN 1 ELSE 0 END WHERE managed = 1"
    )
    with op.batch_alter_table('model_endpoints', schema=None) as batch_op:
        batch_op.drop_column('live_status')
        batch_op.drop_column('managed')
        batch_op.drop_column('provider')

    with op.batch_alter_table('managed_models', schema=None) as batch_op:
        batch_op.drop_constraint('fk_managed_models_endpoint_id', type_='foreignkey')
