import type { ServiceStatus, OverallHealth } from "./model";

export const mockOverallHealth: OverallHealth = {
  status: "warn",
  checkedAt: "2026-06-07T14:02:10Z",
  servicesUp: 5,
  servicesTotal: 7,
};

export const mockServiceStatuses: ServiceStatus[] = [
  {
    id: "svc-vector",
    name: "VECTOR SEARCH",
    status: "nominal",
    latencyMs: 18,
    detail: "ChromaDB · 4214 docs · 384D",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
    ],
  },
  {
    id: "svc-websearch",
    name: "WEB SEARCH",
    status: "nominal",
    latencyMs: 38,
    detail: "SearXNG · /search healthy",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "warn",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
    ],
  },
  {
    id: "svc-email",
    name: "EMAIL SYNC",
    status: "warn",
    latencyMs: 512,
    detail: "IMAP · last sync 14m ago",
    degradationNote: "Keyword fallback active — semantic ranking offline",
    history: [
      "nominal",
      "nominal",
      "warn",
      "warn",
      "nominal",
      "nominal",
      "nominal",
      "warn",
      "warn",
      "warn",
    ],
  },
  {
    id: "svc-push",
    name: "PUSH (NTFY)",
    status: "nominal",
    latencyMs: 24,
    detail: "ntfy.sh · topic connected",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
    ],
  },
  {
    id: "svc-model",
    name: "MODEL ENDPOINT",
    status: "nominal",
    latencyMs: 12,
    detail: "Ollama · :11434 · qwen2.5-32b",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
    ],
  },
  {
    id: "svc-embed",
    name: "EMBEDDINGS",
    status: "alert",
    latencyMs: 0,
    detail: "all-MiniLM-L6-v2 · reindex required",
    degradationNote: "Collection schema mismatch — new docs not indexed",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "warn",
      "warn",
      "alert",
      "alert",
      "alert",
      "alert",
    ],
  },
  {
    id: "svc-storage",
    name: "OBJECT STORAGE",
    status: "nominal",
    latencyMs: 8,
    detail: "Local · data/ · 2.4 GB used",
    history: [
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
      "nominal",
    ],
  },
];
